### ISSUE TITLE
Triggering the exit to MAP33-Betray in Doom 2 BFG IWAD MAP02-Underhalls takes me to MAP01-Entryway instead of MAP33-Betray

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#1011]
### Background

Version of Chocolate Doom: Git 31.03.2018

Operating System and version: Windows 7

Game: (Doom/Heretic/Hexen/Strife/other) All

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: Triggering the exit to MAP33-Betray in Doom 2 BFG IWAD MAP02-Underhalls takes me to MAP01-Entryway.

Expected behavior: It should take me to MAP33.

P.S. Crispy Doom 31.03.2018 build that has merged this code handles the transition to MAP33 correctly.

**Comment by fabiangreffrath** [comment]
What do you expect, there was no map33 in vanilla doom. This has always been a crispy-specific addition.

**Comment by Zodomaniac** [comment]
So 'Emulate Doom2 map33 behavior' does not mean handling the transitions to and from that map?
I also IDCLEVed to MAP33, completed it, and the game errored out with this 'Bad':
![bad_map33_choco_completion_bug](https://user-images.githubusercontent.com/15119473/38163172-2ef94bb6-34f8-11e8-9298-b0d20423c36f.png)
I suppose there should be a more appropriate error message :)

**Comment by JNechaevsky** [comment]
This must be a "Bad music number" message.

@fabiangreffrath, FYI, cutoffs of `I_Error` messages is a bug which comes with Windows Aero theme. For example, Windows 7 classic and basic themes are not affected. On Windows 10 situation is more nontrivial.

I have done a demystification here: https://github.com/chocolate-doom/chocolate-doom/commit/0b50fbde6a49250d4372a3255b1e1fd451326abe#commitcomment-27633793

Solved it for myself by using Windows native `MessageBoxW` instead of `SDL_MessageBox` for `I_Error` messages. For some reason, situation with cutoffs of Russian chars _was_ even more worse: https://github.com/JNechaevsky/russian-doom/commit/fe2f63989f29c28c700530289edef8b42252c582

**Comment by Zodomaniac** [comment]
@JNechaevsky In my build comprised of with daily build EXEs and Crispy 5.1 DLLs those messages are not cut off :) Like this
![git](https://user-images.githubusercontent.com/15119473/38163718-56b51b54-3501-11e8-8886-a241ea1df5b7.png)

**Comment by Zodomaniac** [comment]
@JNechaevsky In @chungy 's build https://chungy.keybase.pub/chocolate-doom-3.0.0-60-g0b50fbde-win32.zip those messages are not cut off :)
![bad v_drawpatch](https://user-images.githubusercontent.com/15119473/38165980-d05245d6-3524-11e8-910d-3d4656e0b5a8.png)

**Comment by JNechaevsky** [comment]
/summoning @chungy then!

**Mike**, is it a pure MSYS build? Or possibly some kind of magic was applied?

**Comment by chungy** [comment]
Was done with mingw-w64 on Linux, no magic really.

We might just take your Win32 MessageBox stuff from Russian-Doom, perhaps.

**Comment by JNechaevsky** [comment]
Well, messages cutoff getting really weird route now. Couple of months ago I was having an additional investigation, and back then it was figured out that English chars are cut on Russian Windows 10 LTSB edition, which is not available to the wide public.

I think I still can't suggest anything else than it's a Windows Aero related bug, because on Linux's console output is everything fine with both English and Russian messages. My attempts to google what the heck is happening in combination of `SDL_ShowSimpleMessageBox` and Windows Aero gives nothing...

So yeah, using a `MessageBoxW` seems to be _(probably)_ a good way to go. Please note, I'm **not** suggesting using a `MessageBox` because it's does not working proper with UTF-8 locale and does not supporting char converting tricks (there are few possible, I'm using most simple in my project).

Anyways, this topic require additional discussion. All a can guarantee in my approach is all `I_Error` messages are working fine on Windows now without any cutoffs, but probably there is a more correct implementation can be done.

**Comment by JNechaevsky** [comment]
An examples of `MessageBoxW` on Windows 7 and 10. 

![](http://priscree.ru/img/838e85cb08ed92.png) ![](http://priscree.ru/img/e6c7a862ec9cb6.png)
