### ISSUE TITLE
GUS music instruments are wrong

### ISSUE THREAD

**Issue by vanfanel** [chocolate-doom/chocolate-doom#1016]
Another bug I have found:

Using the GUS music playback, along with the recommended patchset from the docs (in https://www.doomworld.com/idgames/music/dgguspat) music has some strange instrument choices not present in other sourceports.
For example, try E1M2 from DOOM, and let the music play. You will soon hear a flute in the place of a percussion effect.
Also, E1M1 from DOOM2 sounds strange.

**Comment by fragglet** [comment]
This is a vanilla bug: https://doomwiki.org/wiki/GUS_instrument_mappings_bug

There are two workarounds:
1. Instead of using GUS emulation, use "Native MIDI" and point Timidity configuration at the timidity.cfg file included in that .ZIP
2. The problem can be fixed using a modified DMXGUS lump that works around the issue. You can extract the one from Freedoom and use that, and it should sound a lot better. I keep meaning to upload a copy to idgames because it makes sense to have a standalone fix.

**Comment by vanfanel** [comment]
@fragglet : Thanks for the tip! The "Native MIDI" solution works perfectly well!
