### ISSUE TITLE
Weird wad-specific mouse problem

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#103]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/103/) on Sourceforge by [porschemonty](https://sourceforge.net/u/porschemonty/profile/), 2010-12-08 10:42:17:

This may just be something wrong with my legacy hardware, but here's what happens anyways. After launching immy-dm with the suggested commands \(-server -deh immy.deh -file immy-dm.wad -respawn -altdeath\) the player starts in a certain position, facing a somewhat distant wall and completely standstill. However, after launching immy-dm via COMP-DM.EXE in Vanilla Doom \(on a real 486\), the player moves about a couple of steps backwards before stopping, plus you can see he's facing the aforementioned wall in a slightly different angle. This behavior is perfectly consistent here; the player always stops exactly on the same spot in the exactly the same position \(confirmed with screenshots\)

Now here's the interesting part. Even though this ONLY seems to happen with immy-dm.wad,  I can just disable the mouse input from vanilla setup.exe and then it will behave exactly like Chocolate Doom, no moving backwards, exact same position and angle, etc.

Any idea what's going on here? needless to say, immy-dm vanilla demos would likely desync with Chocolate Doom if mouse input were on during recording, given that the player essentially starts in a different position.

Tested with [r2202](//github.com/fragglet/chocolate-doom/commit/3f3efe93eb84ce222dcdb8469f66bcd0fae2e74d) on WinXP Pro SP3.

Regards.

**Comment by CapnClever** [comment]
I agree with never_again: this is almost certainly the effects of awkward mouse-grabbing into the game from those vanilla-compatible launchers. Who knows what COMP-DM.EXE does with the input? (I encountered a similar problem network games via one computer: both screens wanted to grab the mouse and it made them turn in odd ways at startup, fixed by disabling mouse grab.)

As to why I wouldn't expect this to cause desync, it is well-known by runners of the game that you can buffer your inputs when directly warping into the level from startup. This allows for instantaneous speed and angular displacement, and provides single-level demos to get a "head start" which is accepted practice and is recorded by the demo without a problem.

I vote to close this issue. Chocolate Doom shouldn't be responsible for launcher bugs.
