### ISSUE TITLE
Segfault when loading map with no player 1 start

### ISSUE THREAD

**Issue by mfrancis95** [chocolate-doom/chocolate-doom#1049]
[https://github.com/fabiangreffrath/crispy-doom/issues/315](https://github.com/fabiangreffrath/crispy-doom/issues/315)

**Comment by fragglet** [comment]
Happy with adding something similar, with a couple of comments:

* The check should be if there is no player 1 start, since I believe that's what causes the crash, not the lack of things. Maybe player N start where N=consoleplayer, to cover the multiplayer case too?
* I believe it crashes in vanilla, so some mention in the error message of "(vanilla crashes here)" would be helpful

**Comment by mfrancis95** [comment]
The segfault occurs on line 235 of p_user.c. Basically the first call to `P_PlayerThink`, since it's given a bad player pointer.
