### ISSUE TITLE
Chocolate Heretic Options Menu Bug

### ISSUE THREAD

**Issue by ArchVileF** [chocolate-doom/chocolate-doom#1058]
Hey, sorry if this isn't the right place for this; if that's the case my apologies and I'll have to find the correct place to report this. Also, idk if this is a result of something on my end, but hopefully we can figure it out together. Thanks for creating and maintaining this awesome port :)

### Background

Version of Chocolate Heretic: 2.3.0 and 3.0.0

Operating System and version: Win 10 64-bit (maybe this is the problem?)

Game: Heretic

Any loaded WADs and mods (please include full command line): Happens with nothing extra loaded, both at the title screen and in-game.

### Bug description

Observed behavior: In 2.3.0, when I would select "Options" in the menu, chocolate would crash and say something along the lines of "Bad Lump _______." Sorry I can't remember the exact message at this point; when I saw that I quickly went and checked for a new version, downloading 3.0.0. 
In 3.0.0, going to the options menu causes a crash as well, but this time literally just says "Bad" and it's not centered in the box. Idk if that latter part matters, but I feel like either I'm not getting the full error message to report or somebody just knows I've been naughty, heh. 

Expected behavior: Go to options menu. Honestly idk what I was even gonna change at this point, heh; mouse sens is in setup.

Thanks in advance :)

**Comment by chungy** [comment]
I suspect you were actually getting `Bad V_DrawPatch` due to a bug in Doom and Heretic that crashes the options screen when the mouse sensitivity is set too high. See: https://www.chocolate-doom.org/wiki/index.php/FAQ#Why_does_the_game_crash_when_I_access_the_options_menu.3F

The other issue about seeing "Bad" and not the rest of the message appears to be a Windows bug... we had a discussion in another issue but I can't find it. :(
