### ISSUE TITLE
Less code repetition?

### ISSUE THREAD

**Issue by mfrancis95** [chocolate-doom/chocolate-doom#1126]
Doom and Heretic, for instance, have identical `P_LoadLineDefs` functions. Thoughts on refactoring these cases to be written once and used by the games that need them?

**Comment by fragglet** [comment]
I considered this back when I was working on raven-branch - the natural tendency for any programmer is of course to try to eliminate duplicated code as it's accepted wisdom.

However nowadays I'm of the opinion that it's actually unnecessary and I'd rather keep the codebases for different games separate. My reasoning is:

* The project philosophy means that they aren't likely to get many changes anyway
* Factoring out into common code will mean that the codebase will become more "fragmented" - at the moment there's a fairly clean separation between "the game code" and "the low-level/common code". For purely academic purposes of studying the source code, having the game code all in one place probably makes it nicer to deal with.
* Current rendering is accurate to the level of being pixel-perfect identical with vanilla Doom, which is a nice property to have. There's a "danger" that deduping will break vanilla compatibility, especially if we go down this path to the level of merging stuff like game physics logic.

I'm actually of the opinion that a few bits of the common code should probably be reduped back into the game directories. For example the code handling cheats got deduped and there's actually a bug because of it where it (you can't type SATANRA in hexen to get god mode + full weapons).

I'm going to close this for now but happy to hear other opinions.
