### ISSUE TITLE
-shorttics command line option is not documented in readme

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#1143]
The `-shorttics` command line option that forces low-resolution turning even when not recording a demo which is useful for demo run practice should be documented in CMDLINE document (btw, where in the repository is this file?)
It was introduced with commit https://github.com/chocolate-doom/chocolate-doom/commit/11035e797c56d66d3afebdc5041a7fce26aba36d

**Comment by jmtd** [comment]
Command-line arguments are documented individually in the source code directly, using comments of a particular format. The "docgen" script then pulls them out to build the CMDLINE file (and other files). A description of the scheme is in the docgen script here: https://github.com/chocolate-doom/chocolate-doom/blob/master/man/docgen

The comment should probably be added somewhere around here, https://github.com/chocolate-doom/chocolate-doom/blob/5329fb5d75971138b20abf940ed63635bd2861e0/src/doom/d_net.c#L198

although there might be some problems since that chunk of code checks three parameters in the same statement.

**Comment by AXDOOMER** [comment]
Would it be acceptable to do it like that?


    connect_data->lowres_turn = (M_ParmExists("-record")
                             && !M_ParmExists("-longtics"))

    // @category net
    //
    // Use shorter tics
    //

                              || M_ParmExists("-shorttics");

I would like to have an opinion, although, this is a better approach:


    connect_data->lowres_turn = (M_ParmExists("-record")
                             && !M_ParmExists("-longtics"));

    // @category net
    //
    // Use shorter tics
    //

    connect_data->lowres_turn = connect_data->lowres_turn || M_ParmExists("-shorttics");

**Comment by fabiangreffrath** [comment]
How about this?

```
int shorttics;

// @category net
//
// Use shorter tics
//

shorttics = M_ParmExists("-shorttics");

connect_data->lowres_turn = (M_ParmExists("-record")
                         && !M_ParmExists("-longtics"))
                         || shorttics;
```

**Comment by AXDOOMER** [comment]
It's cleaner and more understandable. It's worth using an extra variable for clarity because the compiler will do the optimization.

**Comment by jmtd** [comment]
> How about this?

If `simplecpp` can pull it out like that, then yeah I think this is a good approach

**Comment by Zodomaniac** [comment]
So should @fabiangreffrath 's approach be committed at last?
