### ISSUE TITLE
detect and use python3 during build

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#1158]
I just realized that the only reason why I still have python 2 installed is for building Chocolate Doom and because it only searches for and detects an executable called `python` -- which is python2 on my systems whereas python3 is explicitely called so.

I guess we could change
```
AC_CHECK_PROG(HAVE_PYTHON, python, true, false)
```
to
```
AC_CHECK_PROGS(HAVE_PYTHON, [python python3], false)
```
in `configure.ac` but then we would still be calling our python scripts with the default `#!/usr/bin/env python` shebang line. So, these would have to get turned into templates with the executable name of the python interpreter set at buld time.

Do you think this is worth the effort? Or is there a simpler solution that I just cannot see? Or should we leave it up to the system admin to have the preferred python version available under that executable name?

**Comment by fragglet** [comment]
I kind of think that we should leave it up to the sysadmin to decide. However, I'm totally in favour of making the Python scripts Python 3-compatible. Is there a way we can get Travis to do builds with /usr/bin/python -> python3 ?

**Comment by chungy** [comment]
I believe all the scripts are already python3 compatible, the only issue is whether `python` points to 2 or 3 and it seems Fabian's system doesn't have plain `python` without python2 installed.

**Comment by fabiangreffrath** [comment]
Indeed, our scripts are already python3-compatible, I checked that. It is just that both Debian and MSYS2 have python linked to python2 and there is currently no way in our build system to enforce using python3.

**Comment by jmtd** [comment]
@fabiangreffrath 
>So, these would have to get turned into templates with the executable name of the python interpreter set at buld time.
>
> Do you think this is worth the effort? 

I personally don't. I'd rather we moved to hard-coding python3 instead of hard-coding python2 (what we do now effectively).


@fragglet 
> I kind of think that we should leave it up to the sysadmin to decide.

Are you aware of any systems/environments where Python 3 is not easily available?

@fragglet 
> Is there a way we can get Travis to do builds with /usr/bin/python -> python3 ?

I don't know whether this is possible or not; if possible it's fine to do this for a test environment like Travis, but note that [Python themselves recommend against python invoking python3](https://www.python.org/dev/peps/pep-0394/#recommendation).

My take was always to consider Python 3 to be a completely different language than Python (2).

**Comment by fragglet** [comment]
Okay, since Python is optional for build anyway, I suggest we just go ahead and replace all instances of `#!/usr/bin/env python` with `#!/usr/bin/env python3`.
