### ISSUE TITLE
Issue with FLAC

### ISSUE THREAD

**Issue by buvk** [chocolate-doom/chocolate-doom#1178]
When using the FLAC digital music pack with chocolate-doom-20190607-win32, there is an obvious audio hiccup at the beginning of a song.  The first half-second or so of a song is repeated. This also happens every time a song loops.

This issue does not occur with OGG.

This issue is not present in Chocolate Doom v3.0.0.

The issue can be resolved by replacing the SDL2 dll files with older versions (E.g. the ones packaged with Crispy Doom 5.5.2).

**Comment by shoober420** [comment]
I get stutters with FLAC music packs as well when the song begins its loop. I’m on Arch Linux with the latest SDL2 git builds.

**Comment by XxMiltenXx** [comment]
While replacing the DLLs with the ones from Crispy Doom 5.5.2 fixes the issue on first playback, the issue still persists for metadata loops. Whenever the song tries to loop, it'll have the same stutter again (playing the the first ~100 ms twice), regardless of which DLLs used.

While OGGs work fine on the first playback, metadata loop create the same stuttering for me when it tries to loop. So I don't think this issue is only related to FLACs.

I am using Windows 10 64-Bit.

**Comment by buvk** [comment]
The latest version of SDL mixer resolves the hiccup at the beginning of a song.

Version tested: https://github.com/libsdl-org/SDL_mixer/releases/tag/release-2.6.1

**Comment by fragglet** [comment]
Great! So we just need to update chocpkg to use the new version.

**Comment by buvk** [comment]
The hiccup is still present in the latest autobuild.

**Comment by FozzeY** [comment]
The new version of SDL_mixer is not available in the current LTS release of Ubuntu yet.
