### ISSUE TITLE
PC speaker effects don't play when using OPL MIDI

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#1184]
HEAD version. Not sure when this broke.

**Comment by Vomitlord** [comment]
for me all fine. Using 3.0.0

**Comment by NY00123** [comment]
Confirmed as broken for me with the PC Speaker SDL driver. It's working with the Linux driver.

Reverting opl_sdl.c:OPL_SDL_Init to call Mix_HookMusic instead of Mix_SetPostMix fixes this, but given the git log, this may also lead to a breakage.

Referenced commits: 073e710f685a10c2084f6c04fbc4fe7c87530d93, 3bde136c60ba10dc080bc1060a6c039f94d7d147

**Comment by drfrag666** [comment]
This thing has resurfaced in https://github.com/fabiangreffrath/crispy-doom/issues/748
