### ISSUE TITLE
In Program Files, Setup doesn't save unless there is already an existing a .cfg file

### ISSUE THREAD

**Issue by wfong714** [chocolate-doom/chocolate-doom#1189]
### Background

Version of Chocolate Doom: 3.0.0-win32

Operating System and version: Windows 7 Professional - Service Pack 1

Game: (Doom/Heretic/Hexen/Strife/other): Doom

Any loaded WADs and mods (please include full command line): DOOM.WAD, DOOM2.WAD

### Bug description

Observed behavior: When I extract Chocolate Doom to my Program Files folder and run crispy-doom-setup.exe, it doesn't save a .cfg file unless there is already an existing one there.  This is likely due to folders in Program Files defaulting to read-only.

Expected behavior: crispy-doom-setup.exe always saves a .cfg file when saving settings.

Recommended Fix: You should be able to get around the read-only behavior of Program Files by including a default.cfg and/or crispy-doom.cfg file in the zip folder.  That way, the setup program won't be trying to create one while Windows disallows it.

**Comment by chungy** [comment]
Program Files shouldn't be managed manually, and since Windows Vista, there are all kinds of redirections applied to it so Win9x-style programs can continue to operate under a restricted environment.

I'm going to call this Not a Bug since it is running against the design and intended use of the Windows operating system. Extract and use Chocolate Doom only in user folders as is the supported practice.

**Comment by fragglet** [comment]
I think you're holding it wrong - if you place Chocolate Doom somewhere that it can't save a config file, you shouldn't be surprised that it can't save a configuration file.

I'm going to agree that this is not a bug and close summarily.
