### ISSUE TITLE
Feature Request: Optionally Raise Some or All Vanilla Engine Limits

### ISSUE THREAD

**Issue by HollowedEmpire** [chocolate-doom/chocolate-doom#1219]
First off, I love Chocolate Doom and how accurate and true it is to the original executables - right down to bugs.

Though one particular aspect that I feel may be good to be able to alter is the static limits of the engine, such as the visplane limits. Preferably this could be done as an extra command line argument or configuration setting. When not specified, the normal limit values can be used as a default.

These limits in the engine have no real affect on how the game is actually _played_, so I feel providing an optional way to adjust them would still be true to the _vanilla experience_ and not go against the philosophy of the project. It's akin to how all the networking changes _aren't_ 'true to the original' Doom, or how the Vanilla Save Game Limit or Vanilla Demo Limit are already optional changes you can make. All these changes are to give the _vanilla experience_ a greater range of access, just as they are all equally not 'true' and are not 'pure' to the original.

To make the code change as minimal as possible, it could be as simple as specifying numbers for the limits (i.e. visplane array size). One could simply set them to high values in order to run more intensive maps. Another possible and more elegant solution could be letting Chocolate Doom read the map data and set the array limits dynamically at map load time to match what is present.

I'm sure I'm not the only one who would love to use Chocolate Doom for SiGiL and other maps that are otherwise only incompatible due to these hard coded limits. It's quite annoying juggling multiple ports solely because of this single aspect alone, especially that it doesn't affect the _vanilla experience_ in any way - or at least much less so than the changes already put in and present in Chocolate Doom.

**Comment by chungy** [comment]
This is beyond the scope of Chocolate Doom, but you may be pleased to know that [Crispy Doom](https://www.chocolate-doom.org/wiki/index.php/Crispy_Doom) already accomplishes the desire to remove vanilla limits.

**Comment by HollowedEmpire** [comment]
Thanks, though I already have tried Crispy. Not a fan unfortunately, there's too much changed with it and may as well use any given handful of ports at that point.

I'm curious though why it would be considered beyond the scope of the project. At face value, this seems to be a pretty arbitrary considering the things already changed and different in Chocolate from the original game. Could I ask for you to shed a little more light on where the line is drawn at? It'd give at least some sort of resolve and explain the mindset.

**Comment by HollowedEmpire** [comment]
Also I'd like to point out one of the core tiers from PHILOSOPHY.md: "The surrounding aspects of the game that aren’t part of the central gameplay experience can be extended as long as there’s a good reason and Vanilla behavior is respected." 

What I'm proposing is being able to load countless maps and (more or less) an official Episode 5 for Doom, all of which are fully compatible with Vanilla Doom outside the limits. That seems to fall _precisely_ under that tier, does it not? :\  This is why I'm confused by you stating it is 'beyond the scope'.

**Comment by Kroc** [comment]
It's important that Choco-doom glitches and crashes _exactly_ the same way that the original DOS executable does; otherwise it doesn't solve the problem of allowing people to test against vanilla _behaviour_. If choco-doom doesn't behave the same as doom.exe did in 1993 then it's not "vanilla" compatibility people are testing, it's "chocolate" compatibility! :)

**Comment by HollowedEmpire** [comment]
But wouldn't the optional extended formats offered by Chocolate go against what you just said? For example the Vanilla save game limit and Vanilla demo limit removal options. Those are not 1993 compatible and thus would go against the behavior.

And additionally this is why I said it should be an optional parameter to up the limits. So if you didn't specify to extend the limits, it would have the same limits and _would_ crash in the exact same manner as the 1993 version, and thus make the compatibility point moot.

**Comment by fabiangreffrath** [comment]
> Thanks, though I already have tried Crispy. Not a fan unfortunately, there's too much changed with it

Yes? What exactly?

> I'm curious though why it would be considered beyond the scope of the project. 

Think about Chocolate Doom as a research project to replicate Vanilla Doom's behavior in the most precise, convenient and portable manner. It was never meant to play Sigil or any other limit breaking map or episode. And this won't change. You're asking at the wrong place. Also, I don't see why this would still be unclear after reading the philosophy document?

**Comment by HollowedEmpire** [comment]
> Yes? What exactly?
I thought it would be self explanatory... but just open up Crispy and refer to the multiple pages of options.

> Think about Chocolate Doom as a research project to replicate Vanilla Doom's behavior in the most precise, convenient and portable manner. It was never meant to play Sigil or any other limit breaking map or episode. And this won't change. You're asking at the wrong place. Also, I don't see why this would still be unclear after reading the philosophy document?

Let me reiterate pillar 2 and what I said about it above. It makes it very unclear why this optional limit raise would be disallowed, as it falls directly within the pillar's requirements (or at least to the same degree the vanilla demo and save file breaking already allowed in Chocolate).
> Also I'd like to point out one of the core tiers from PHILOSOPHY.md: "The surrounding aspects of the game that aren’t part of the central gameplay experience can be extended as long as there’s a good reason and Vanilla behavior is respected."
>
>What I'm proposing is being able to load countless maps and (more or less) an official Episode 5 for Doom, all of which are fully compatible with Vanilla Doom outside the limits. That seems to fall precisely under that tier, does it not? :\ This is why I'm confused by you stating it is 'beyond the scope'.

And if it is trying to be a research project specifically aimed to be most compatible, why do you allow breaking of vanilla limits for demos and save files then? That completely destroys the point to selectively allow non compatible aspects but not others.

If you allow for setting the array sizes of the static limits, you could allow raising limits while changing virtually nothing but a #define into a variable set by command line. If the values are left as default values, then you will have _exactly, 100%_ the same vanilla behavior. This would not change compatibility whatsoever, unless you _specifically_ tell it to do so - just as you can do with vanilla breaking save and demos Chocolate can produce. So my main question is, what is the defining difference between that vanilla breaking aspect and this proposed one when they are all optional and don't actually affect even how it crashes when disabled?

**Comment by fx02** [comment]
Heh, you can try Competiton Doom, it's Choco with limits removed and few additional tweaks which should not bother you.
https://github.com/fx02/cndoom/releases/tag/v3.0.0-alpha2

**Comment by HollowedEmpire** [comment]
Thanks fx02. I'll have to give it a closer look, but it initially seems it's pretty close to what I'm looking for - though the future plans of bringing the Crispy HUD and potential inability to make vanilla compatible demos and saves is a bit worrisome.  :\

Once I get a slice of time, I'm now planning to just fork Chocolate and make a quick hack to allow optionally specifying the limit sizes. Still will be 100% vanilla compatible and would be able to test 100% compatibility with vanilla map limits with the implementation I'm doing. 

Was sort of hoping I wouldn't need to do that, but it's apparent now that there really is just arbitrary lines drawn on what vanilla features are allowed to be optionally broken or not in Chocolate; and trying to find reason or explanation to this has gotten me nowhere. At least I know there are quite a few other people who'll enjoy it, based on the numerous posts I've come across also requesting this.

**Comment by fragglet** [comment]
> What I'm proposing is being able to load countless maps and (more or less) an official Episode 5 for Doom, all of which are fully compatible with Vanilla Doom outside the limits. That seems to fall precisely under that tier, does it not? :\ This is why I'm confused by you stating it is 'beyond the scope'.

Hi @HollowedEmpire, I appreciate you feel really strongly about this. You aren't the first to ask for this feature and the decision was made some time ago. Maybe I can help to bring some clarity about the rationale.

I'd draw your attention to a contradiction that you've made yourself here in your comments - not because I'm trying to criticize, but just because it helps illustrate my point. You say that you dislike the fact that Crispy Doom has "multiple pages of options" and yet what you are asking for is another option for Choco (probably multiple options, because Vanilla Doom has many different limits).

I'm inferring from what you say that what you like about Choco is the fact that it has a sparse, minimalist set of options, and this is not a coincidence. It's a consequence of the fact that the project has a deliberately restrictive, minimalist philosophy that is intentionally designed to reject most feature requests. I made a technical decision when starting the project - it isn't going to play every Doom map ever made - and I've stuck with it.

Your request is perfectly reasonable in isolation but the problem is that there are many just like it - "I love Chocolate Doom but I wish it just had *X*" where X can be any one of: higher resolutions, uncapped framerate, removed limits, better networking, etc. etc. Plenty of other source ports already exist which do those other things - Choco doesn't. That's just how it is and what the project's about. If we added these features it would lose the property that both you like and I like - it's minimalism and the fact that it's just Doom, nothing else.

I hope that makes things a bit clearer to you. In your last comment you describe it as an "arbitrary line" and I really would dispute that - I can tell you that both personally and as a team we have put a lot of thought and discussion into the [PHILOSOPHY](https://github.com/chocolate-doom/chocolate-doom/blob/master/PHILOSOPHY.md) document. I think you'll find that if you look through past discussions, very few things in this project are ever arbitrary.

One thing in particular I'd point you is that PHILOSOPHY is very careful to define what "vanilla" means - Vanilla Doom is DOS Doom v1.9. So for example when you say:

> I'm now planning to just fork Chocolate and make a quick hack to allow optionally specifying the limit sizes. Still will be 100% vanilla compatible

the definition of "vanilla" becomes muddled, since vanilla has limits. Mappers are clear when they make levels for Doom to distinguish between "vanilla" and "limit removing", and it's not true that SIGIL or any other limit-removing levels are vanilla compatible. And that perhaps cuts to the heart of the whole point I'm trying to make - it's not just an arbitrary line, vanilla Doom is the yardstick we measure against, and it defines the scope of what the project's about.

**Comment by fabiangreffrath** [comment]
I guess with "arbitrary line" he meant that we already offer to remove the Vanilla savegame and demo size limits. And indeed, I find myself unable to give any good reasoning why these two limits for all things are removed but any others aren't.

**Comment by fragglet** [comment]
For demo size the rationale is pretty simple - vanilla Doom has the `-maxdemo` command line argument, so it's equivalent to just setting that to an arbitrarily large number such that you never meet it.

In the case of the savegame limit I'll admit it's slightly arbitrary, and it's a feature that dates to the first couple of years of the project, when the philosophy was much less codified. I'm skeptical whether we'd add it today, though I'm also loathe to remove it at this point.

**Comment by fragglet** [comment]
A complicated braindump of some extra thoughts around this so that it perhaps doesn't seem quite so arbitrary:

* Savegame limit removal "breaks the rules" but that doesn't mean any other feature request that breaks the rules should therefore be allowed.
* Why I say I'm "loathe to remove it" is a complicated matter that basically comes down to pragmatism, because if it was removed, there are a bunch of prominent "vanilla" (note quotes) map sets which would now become unplayable in Choco unless you never save, and I would be loathe to lose them. In other words I'd probably end up running and maintaining a fork of my own port.
* On the same theme, the feedback I've heard from is that mappers haven't historically taken the savegame limit as seriously as the other limits, so there's a large number of levels which are "vanilla except for the savegame limit".
* You can make the argument that the savegame limit is different in substance to the other mapping limits since it doesn't determine what you can play, only whether you can save or not.
* Vanilla Doom can actually load huge savegames just fine, it's just saving them that it can't do.

**Comment by chungy** [comment]
> You can make the argument that the savegame limit is different in substance to the other mapping limits since it doesn't determine what you can play, only whether you can save or not.

I actually think this point is key. I think breaking free of the savegame limit is a quality of life measure not far removed from demos, windowed mode, or PNG screenshots.

Both it and the demo limits walk the gray-area of the question the philosophy document asks: "Although this is Vanilla behavior, is there anyone who would want this?" — the answer to both of them can be yes and no, depending on context. Chocolate Doom defaults to restricting save games to the same limits as vanilla, and this may be important to any users that frequently switch between Vanilla and Choco.

**Comment by HollowedEmpire** [comment]
@fragglet 
Thanks for taking the time to explain this further, I do really appreciate it. Though unfortunately I still don't feel any closer to really understanding the rationale to let one optional vanilla break exist but not another. Well, besides the *very* thin 'keeping Chocolate closer to Vanilla by not introducing more stuff'.

I don't believe I've made any contradictions, or at least not in the way you were explaining I did. Maybe I didn't write it out adequately enough before, so I'll try to re-iterate it against the points you made to hopefully help clarify my point. The feature I'm suggesting would have absolutely no affect at all on the vanilla experience, outside of getting to actually *have the experience*. I definitely wouldn't side with any of the counter changes you suggested to mine. Increased frame rate, increased resolution, changed networking... those type of changes would affect the vanilla experience and definitely would be 100% against the philosophy document. Chocolate should only have changes that can give greater access and range to the vanilla experience, which I feel experiencing these otherwise vanilla compliant maps is perfectly acceptable; but *only* as something optionally! It *shouldn't* be the default behavior to accommodate limit breaking maps and I would fully agree with that. But I feel there is no reason there can't be an option to allow for using these maps so people can get the 'vanilla experience' with them. That's sort of what I feel is the entire point of Chocolate - bringing the vanilla experience into the present.

I'm not quite sure why you feel the simpler approach I suggested for the limit raise would suddenly make the vanilla compatibility muddled for Chocolate. An array is still an array. An array created by a variable with the value of 127 would be exactly the same size as an array was created by a #define with the value of 127. So if the array sizes are defaulted to vanilla limits, I can't see how that muddles things in any way at all. Of course, if you explicitly tell it to muddle the limits, then obviously that would - akin to the demo and save limits. 

Though the more complicated approach of auto setting the limits I suggested, while still possible to do as arrays and get precisely the same vanilla behavior with defaults, would introduce a lot more non vanilla code; so I can understand that being a potential thumbs down at the very least.

But, it seems at this point though that we will likely just have to agree to disagree. It is only opinion vs. opinion now, and we appear to be unable to see eye to eye on the topic. Likely we will only waste each other's time trying to continue on. I'll just have to take some time over a weekend to make a tiny hack in a fork, and that'll be that. It is unfortunate though that the fork is even necessary for something so incredibly minor. But at least this way everyone else who also requested this feature can still use Chocolate Doom's exceptional vanilla experience and have the option play otherwise fully compatible maps as intended.

I'll just close with thanking you again for taking the time to try and explain this further. And thank you and everyone else who worked on and created Chocolate. It really is quite exceptional and amazing software, even despite this hold back it insists to carry. I have used Chocolate as my choice Doom port for years, and is why I was particularly interested to try and understand why something I feel would fit it perfectly as a non-disruptive option, apparently cannot.

**Comment by fragglet** [comment]
I agree that a fork is the right approach here and I just want to say no hard feelings. There are many different forks of Chocolate Doom at this point and I always welcome people more (indeed, the codebase is designed to be fork-friendly). Please do stay in touch and feel free to add a page for it on the website if you like.

**Comment by fabiangreffrath** [comment]
> That's sort of what I feel is the entire point of Chocolate - bringing the vanilla experience into the present.

It is not necessarily the *experience* (you can have that similarly with other ports like e.g. Eternity or PrBoom+). Choco's aim is to *replicate the behavior* of DOOM.EXE on modern systems. Of course, the former follows from the latter.

That's why I brought in the research project comparison. The question is "what would happen in DOOM.EXE?", not "how would it feel in DOOM.EXE?". I hope you see the difference.

**Comment by HollowedEmpire** [comment]
@fabiangreffrath 
Again, then why do you allow the vanilla breaking extended save file and demo formats still? Those *don't replicate the behavior of the DOOM.EXE whatsoever*. It's very hypocritical to try and justify not adding the *option* to increase the level limits for this reason, when you *already* provide options that *don't* replicate DOOM.EXE's behavior.

**Comment by fabiangreffrath** [comment]
@fragglet literally just explained that.

**Comment by HollowedEmpire** [comment]
... 
He explained why they are *there*, but that doesn't automatically resolve them of being hypocritical. Having those features present makes Chocolate defy it's own principles and philosophy. You would need to remove them in order to *actually* be true to Vanilla.

Also if you didn't notice, fragglet also *agreed* that it was somewhat arbitrary they are there and likely acknowledged that they are indeed against the philosophy of Chocolate.

**Comment by HollowedEmpire** [comment]
So again, the reason of "staying true to DOOM.EXE" has no legs to stand on when you *already* defy it. Only after removing the other philosophy offending features would it make any sense to argue that; which I would be wholeheartedly for and would also then agree that this feature request would be totally invalid.

Basically, either please actually be true to DOOM.EXE and remove all non vanilla breaking aspects or don't arbitrarily deny options that don't change the game play and presentation of the game since there are already some present that do *exactly* that. I don't know why this seems to be such an "out there" concept to have consistency.

**Comment by fragglet** [comment]
Hi @HollowedEmpire, in keeping with your previous comment:

> But, it seems at this point though that we will likely just have to agree to disagree. It is only opinion vs. opinion now, and we appear to be unable to see eye to eye on the topic. Likely we will only waste each other's time trying to continue on. 

I think we're just going round and round in circles in this point and nothing's likely to be said that hasn't already been said at length. With that in mind I'm going to lock the conversation since I don't think there's any more productive to be said. I'd rather avoid this devolving into a flamewar because I'd like us to stay on friendly terms so we can work together in future.
