### ISSUE TITLE
OpenMP to parallelise loops?

### ISSUE THREAD

**Issue by mfrancis95** [chocolate-doom/chocolate-doom#1231]
Thoughts on using OpenMP to parallelise certain iteration-heavy loops in the code?

This would be an optimisation sort of in the likes of https://github.com/chocolate-doom/chocolate-doom/pull/1125.

**Comment by fragglet** [comment]
I don't think it's worth it.

Several years back when we had the software screen scaling code I would have suggested maybe using it for that, since it accounted for the bulk of all CPU usage. Nowadays we use SDL to do that in hardware for us. The renderer only draws a 320x200 VGA screen and modern CPUs can blaze through the whole thing. Optimizing this stuff only makes sense on old DOS machines where OpenMP won't work anyway.

**Comment by mfrancis95** [comment]
I was thinking in a non-rendering context. There are cases that don't relate to rendering and don't have some kind of ordering dependency where it could be applied.
