### ISSUE TITLE
Final Doom uses Doom 2 strings if path to IWAD uses foward slashes

### ISSUE THREAD

**Issue by jackrjli** [chocolate-doom/chocolate-doom#1271]
### Background

**Version of Chocolate Doom:** `chocolate-doom-20200414-win32.zip` from latest.chocolate-doom.org

**Operating System and version:** Windows 10

**Game:** Final Doom (TNT and Plutonia)

**Any loaded WADs and mods (please include full command line):** `chocolate-doom -iwad ../iwad/PLUTONIA.WAD`

### Bug description

**Observed behavior:** When using a Final Doom IWAD, Chocolate Doom will display Doom II's strings (i.e. map titles and story text) if the path to the IWAD specified with the -iwad parameter uses forward slashes instead of backslashes. However, the game otherwise loads successfully.

For example,
`chocolate-doom -iwad ../iwad/PLUTONIA.WAD`
will display the title of MAP01 as "Entryway," while
`chocolate-doom -iwad ..\iwad\PLUTONIA.WAD`
will display the correct title, "Congo."

This holds true whether I use a relative path as shown above, or a full path.

I also found that `chocolate-doom -iwad ../iwad\PLUTONIA.WAD` displays the Plutonia title, and `chocolate-doom -iwad ..\iwad/PLUTONIA.WAD` displays the Doom II title.

This doesn't affect Freedoom Phase 2 or FreeDM, i.e. `chocolate-doom -iwad ../iwad/freedoom2.wad` still displays the Freedoom map titles and not Doom II's.

**Expected behavior:** The game uses the correct strings for the IWAD whether the path to the IWAD uses forward slashes or backslashes.

**Comment by fabiangreffrath** [comment]
Indeed, and I have been bitten by this as well in the past. As a matter of fact, Windows accepts forward slashes as directory delimiters since practically forever. So, we should probably either check for both types of delimiters in `M_BaseName()` or introduce something like MBF's `NormalizeSlashes()` [1] and let is pass over path names before parsing them.

[1] https://github.com/fabiangreffrath/woof/blob/81c920c96c7a29038aa811ce363759673e29bbcb/Source/w_wad.c#L96
