### ISSUE TITLE
GetRawInputData

### ISSUE THREAD

**Issue by akw0088** [chocolate-doom/chocolate-doom#1348]
### Background
Obscure issue, but figured I'd mention it

JSLinux/TinyEMU runs Windows 2000 Service Pack 4

GetRawInput is not supported until Windows XP:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getrawinputdata

zdoom 2.8.1 seems to work, also winquake works, figure chocolate doom should also run if linked differently

Looking at the source code (quick grep) I couldn't find a call to this function, and assume it only exists in the user32.lib stub library

Version of Chocolate Doom:
version 3.0.1

Operating System and version:
Windows 2000 Service Pack 4

Game: (Doom/Heretic/Hexen/Strife/other)
Doom

Any loaded WADs and mods (please include full command line):
No

### Bug description
DLL Linker issue
https://i.imgur.com/nQ647Cw.png

Observed behavior:
Application does not start

Expected behavior:
Application should start

**Comment by turol** [comment]
This probably comes from SDL2. I'm not sure we can do anything about that without customizing SDL2. You should ask them if windows XP is still supported.

Also I've noticed windows dll error messages are entirely useless. I've had a program fail to start because I had the wrong bitness SDL2.dll in its directory and the error message was just "program failed to start" or something to that effect.

**Comment by chungy** [comment]
I remember a few years ago, it was still somewhat trivial to make SDL 2.0.x (an early version) run on Windows 2000 by bypassing the XP-specific calls. I don't know if it's still trivial.

At any rate, it is out of scope of this project. SDL2 as-is requires Windows XP at a minimum, and you'll have to put in extra work to port SDL2 to older versions so that Chocolate Doom may run.
