### ISSUE TITLE
Bools use 4 bytes right now. Would you be open to switching to 1 byte bools for efficiency?

### ISSUE THREAD

**Issue by medvednikov** [chocolate-doom/chocolate-doom#1411]
Would you be open to switching to 1 byte bools for efficiency?

If yes, I'll submit a PR.

I was having issues when integrating chocolate-doom with a different project, since it's using 1 byte bools.

Thanks.

**Comment by voodoo84** [comment]
On what platform are you working?

Because on most machines, storing and reading 1-byte anything is not efficient because the hardware accesses the memory in words instead of bytes. So, if you try to read one byte from memory, it has to read 4 bytes on a 32-bit machine and right-shift the upper byte to get your one-byte value, so it's slower. That's why compilers by default do not use packed structures.

**Comment by AXDOOMER** [comment]
This is a good case of "trust the compiler". Programmers have been using 4-byte integers for boolean variables since the beginning of programming on x86, when computers had as low as 640KB of memory. By this standard, it's not being wasteful.

**Comment by fragglet** [comment]
Yes, I agree with @AXDOOMER here. This is a good example of how something can seem more efficient but actually isn't.

**Comment by medvednikov** [comment]
Interesting. 

Why does C99's `_Bool` use 1 byte though?

```
#include "stdbool.h"
#include <stdio.h>
int main() {
    _Bool x = false;
    printf("%d\n", sizeof(x));
    return 0;
}
```

>> 1

**Comment by dumblob** [comment]
First of all, C99 does **not** mandate **any** bit width of the `_Bool` type (it just says it must be able to store 0 and 1). See https://stackoverflow.com/a/8014188 .

OTOH C kind of (mostly) requires each variable to be addressable (`&myvar`) which can't be done with anything smaller than 8 bits on modern machines.

After googling a bit the reason why (some) compilers prefer the `char` width seems just due to specific historical events.
