### ISSUE TITLE
Soundfonts (.sf2) make music volume affect entire sound volume

### ISSUE THREAD

**Issue by rzhxiii** [chocolate-doom/chocolate-doom#1473]
### Background

Version of Chocolate Doom: latest autobuilds (this also happens with locally built Crispy Doom, did not test with latest releases of either Chocolate or Crispy)

Operating System and version: Windows 10 (32-bit)

Game: Doom/Heretic/Hexen/Strife

Any loaded WADs and mods (please include full command line): N/a

### Bug description

Observed behavior: playing with a soundfont (.sf2) set using the setup tool will result in the music volume also affecting sound effects (for example, playing with music volume set to 0 will mute the entire game); this seems to happen regardless of the soundfont used.
Sound volume still affects sound effects, but does not affect music volume.

Expected behavior: music volume should only affect music while using .sf2 files

**Comment by mikeday0** [comment]
I am guessing that Fluidsynth is not actually present so SDL Mixer is falling back to using native MIDI. The music volume affecting overall volume is a known issue on Windows with SDL Mixer and native MIDI.

The .sf2 file path is for Chocolate Doom to pass to Fluidsynth via SDL Mixer. Fluidsynth does not by default come with the Windows releases of Chocolate Doom. (Historically I think Fluidsynth has been predominantly for Linux.) So first, you need to obtain Fluidsynth binaries for Windows, and then place all the dll files in the same folder with sdl2_mixer.dll. And then (assuming your sdl2_mixer.dll was compiled with Fluidsynth support) everything should work as expected.

Otherwise on Windows you have other options for software MIDI such as VirtualMIDISynth and BASSMIDI.

**Comment by rzhxiii** [comment]
Yeah, the lack of Fluidsynth .dll files was the issue.
Still, I jumped on the VirtualMIDISynth wagon because it's easier to use.
Thank you again!

**Comment by mikeday0** [comment]
So I've learned that the official SDL Mixer binaries are in fact **not** compiled with Fluidsynth support. If you want this feature on Windows you need to compile your own SDL Mixer.

I think that Chocolate could actually handle this a little bit better. It's possible to determine at runtime which decoders SDL Mixer has available. I think on Windows we should check if Fluidsynth is available before attempting to use it. If it's not present, fall back to using the native MIDI.
