### ISSUE TITLE
chocolate doom dedicated server player timed out and disconnected

### ISSUE THREAD

**Issue by freeve4h** [chocolate-doom/chocolate-doom#1488]
### Background

Version of Chocolate Doom: 3.0.1

Operating System and version: Linux orangepi debian for hosting the dedicated server and Linux raspberry pi debian 

Game: doom

Any loaded WADs and mods (please include full command line): all wads i have: doom.wad, doom2.wad, tnt.wad, freedm.wad, ect. commandline used is chocolate-server, i joined through chocolate setup

### Bug description

Observed behavior: unable to join my own chocolate doom dedicated server when on different pc

Expected behavior: able to join and play on my chocolate doom dedicated server when on different pc

whenever i try to connect it says "please wait" before then saying "lost connection to server", on the pc hosting the server it says "Client 'freeve4' timed out and disconnected". i have no idea what is happening.

**Comment by hfc2x** [comment]
This is [a known bug](https://github.com/chocolate-doom/chocolate-doom/issues/1443) in the 3.0.1 release that has been fixed in commits since. I know this because I had the same problem months ago.

On Windows, you can use the [latest autobuild](http://latest.chocolate-doom.org/) from the official site. On Linux, you have to clone the repository and [build it](https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Linux_(generic)) with [chocpkg](https://github.com/chocolate-doom/chocpkg).

**Comment by fragglet** [comment]
Closing as per comment.
