### ISSUE TITLE
Map 33 behaviour

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#157]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/157/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2011-04-13 20:15:27:

Their's two behaviour changes.

1- The name of the level in the automap 
(with DOOM2.EXE it's ?* !? /# 8/ ?$@ /* or something like that and Chocolate-Doom.exe is Level 1: Congo)

2- When you end the level 
(DOOM2.EXE will crash with Bad V_DrawPatch right after the switch is pressed and Chocolate-Doom.exe will crash after the intermission screen)

The attached file below contain Map33.wad with a batch working with both engines.

**Comment by CapnClever** [comment]
I tried to reproduce the original reporting in DOSBox but ended up with a completely blank value in the automap instead: looks like it's probably undefined behavior. Also, the "Bad V_DrawPath" error is appropriately shown in Chocolate Doom now, so at least that's taken care of.

As for the Plutonia map name, this occurs in Chocolate Doom 2.2.1, and the reason appears to be how the names are stored. In `hu_stuff.c` there's a character array `mapnames_commerical` that contiguously stores Doom2, then Plutonia, and finally TNT mapnames. Interestingly, verifying this PWAD using Final Doom's DOOM2.EXE shows that vanilla behavior for Plutonia displays the automap name as "Level 1: System Control" (corresponding to TNT map01). Given that, I suppose the most vanilla solution would be to break up `mapnames_commerical` into a group for Doom2 and a group for Plutonia/TNT and allow TNT names to "spill" into Plutonia: not sure if array padding ought to be added to handle 33-35 for the others, but I reckon it looks the cleanest (and is compatible with DOSBox if nothing else).

Additionally, I noticed other inaccuracies between vanilla and Chocolate with respect to the intermission screen:

- In vanilla the word "FINISHED" still appears at the top, albeit on the first line (instead of the second where the map name would be if it existed); in Chocolate 2.2.1 there is no text at the top.
- In vanilla no par time is given (as completely empty, not even :00); in Chocolate 2.2.1 there is instead a par time of :02.
