### ISSUE TITLE
[Question] Music Pack configs

### ISSUE THREAD

**Issue by SirYodaJedi** [chocolate-doom/chocolate-doom#1576]
This is a continuation of the conversation in https://github.com/chocolate-doom/music-packs/pull/3. That repository was archived after my PR was closed, so I was unable to reply to the message:

> Thanks. This is unnecessary by design since the configs work based on the hashes of the music lumps. If you have the Doom and Doom II music packs installed, it just works.

From my understanding of how the music pack system works, the engine reads from a hardcoded list of known hashes, as well as reads the hashes from a `wadname-music.cfg` configuration file. If the files pointed to in the CFG file are not found, then the hardcoded list is used. The [hardcoded list](../../blob/master/src/i_musicpack.c#L146) expects the replacement music files to all be placed in the same folder, which is messy, and leads to [filename conflicts](../../blob/master/src/i_musicpack.c#L357), negating the point of why hashes are used in the first place. Given these issues, I fail to see how the repository is obsolete, as the option for cleaner organization is still there. The [(ill-updated) wiki page](https://www.chocolate-doom.org/wiki/index.php/Digital_music_packs) also still points to CFG files as being the proper way to install music packs, and [the popular music pack providers](https://sc55.duke4.net/games.php#doom) also link to the repo as how to install the packs in Chocolate and Crispy Doom, so people will inevitably still be coming to it regardless.

On a related note, the obsolescence notice in the repo's description refers to `i_musicpacks.c` instead of `i_musicpack.c`.

**Comment by fragglet** [comment]
Hi and apologies because i wasn't expecting that archiving the repository would lock the discussion there. That may have come across as rude and it wasn't my intention.

The repository contains config files for the commercial Doom IWAD music tracks (and heretic, hexen, etc.). The hardcoded list makes it obsolete and is a better solution than having to fiddle around with config files and so on. I get why that may seem messy but it's a lot simpler to just have a folder you can copy the files into. You can still use config files if that bothers you. Keeping the repository around but archived seems appropriate - it's there if you want it but it won't be receiving any future updates. I'd rather not waste people's time by making them think they can send PRs there only to close them.

Some documentation updates are definitely needed. The wiki should be updated (contact me privately via email or discord if you need the sign up password) and someone should contact Brandon Blume to remove the links from his page.

Thanks!
