### ISSUE TITLE
Suggestion for command line consistency

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#212]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/212/) on Sourceforge by [porschemonty](https://sourceforge.net/u/porschemonty/profile/), 2011-11-08 22:52:19:

Here's the issue. Command line arguments such as -window or -nonovert, permanently modify the config. The way I see it, changes should be permanent only if they're made with the setup tool or by directly editing the config file. Command line arguments should not have this power, they should be temporary so that they're no longer used when the command line argument is left out.

Right now the changes have to be undone by hand, and while this is no big deal, it can be sort of inconvenient when you're testing several instances of CD at the same time.

Regards.

**Comment by fragglet** [comment]
So to revisit this, since it's a blocker for sdl2-branch: things have changed a bit and some of the command line flags are no longer present. Here's what we still have:

> -1, -2, -3, -geometry, -width, -height (window size)

> -fullscreen, -window (windowed vs. fullscreen mode)

> -grabmouse, -nograbmouse (mouse grabbing in windowed mode)

> -novert, -nonovert (disable vertical mouse movement)

I still think it makes sense to have the window size arguments affect configuration since it seems like the most intuitive behavior. I'd now add the -fullscreen / -window arguments to that category as well, since with #696 merged we can now dynamically switch between fullscreen and windowed too.

That leaves -grabmouse and -novert which I think should be temporary overrides.

To give some more detail behind my reasoning here and how I'm categorizing these:

If you consider Doom's configuration file variables, they can be generally categorized into "statically configured" (set once in the setup tool) and "dynamically configurable" (can be changed while the game is running). Examples of static variables are: key bindings; sfx and music devices; chat macros. Examples of dynamic variables are: sfx and music volume; screen size; gamma correction level; whether messages are shown. Dynamic variables are always automatically saved and restored the next time the game runs: your volume levels, screen size etc. are remembered.

Configuration file variables have some interaction with command line arguments, but in Vanilla Doom, it is only ever static config variables which are overridden. Examples are -nosound, -nomusic, -nomouse, etc. These are temporary overrides which are not permanent, which makes sense. But there aren't any arguments which override dynamic variables: there's no -screensize or -sfxvolume argument for example.

From the list above: window size and fullscreen are variables which are now entirely dynamic: it's as easy to switch between windowed and fullscreen modes as it is to change the screen size or gamma correction level. I think the principle that "dynamically configurable variables are preserved" is a good one and wins out over "command line arguments are temporary". But for static ones the same reasoning doesn't apply; it makes sense for arguments like -grabmouse and -novert to be temporary overrides to be consistent with everything else.

But one other thing that springs to mind: why do we even have -grabmouse/-nograbmouse and -novert/-nonovert in the first place? Presumably people usually configure these through the setup tool anyway - is there actually any reason to keep these? I think the only one I ever use regularly is -nograbmouse for when I'm running multiple instances at once and don't want them to fight over the mouse focus. IIRC these arguments date to the very early days of the project, before the setup tool existed. Maybe these are dinosaurs that we should just kill.

**Comment by fx02** [comment]
I like to have passable options via command line. I think it could be useful in some situations so I vote for keeping them although I won't mind if we remove them.

**Comment by fragglet** [comment]
Can you name specific circumstances where you've used -grabmouse or -novert, and why you used them?

**Comment by fx02** [comment]
For external launcher? eg. from kodi advancel launcher, doom launcher. As I said I really do not need them but I hate when some option is available in software for years and then they remove it just because they don't us it :)

**Comment by fragglet** [comment]
Okay, but that's not an actual use case. Can you think of any actual situations where you would want to temporarily turn on grabmouse or turn on/off novert? I can't. If there aren't any we should just get rid of them.

**Comment by haleyjd** [comment]
Actually, yes. When debugging choco from Visual Studio, all mouse input needs to be disabled or when a breakpoint is hit, the mouse spazzes out for 10 seconds solid, freezing and then eventually flying all over the screen like it has a mind of its own. I have no idea what causes this as Eternity has never likewise suffered. I usually put these options into the debug launch command line option in VS.

________________________________

**Comment by fragglet** [comment]
And you use -grabmouse or -novert to avoid that? Not -nomouse?

Please note that I'm planning on keeping -nograbmouse for reasons I mentioned above; it's the other ones (-grabmouse; -novert; -nonovert) which are in question here.

**Comment by chungy** [comment]
I'd be in favor of removing all four, honestly. Why is -nograbmouse beneficial compared to -nomouse?

**Comment by haleyjd** [comment]
I think I used -nomouse -nograbmouse


If they are redundant, I wasn't aware of it at the time.

________________________________

**Comment by fragglet** [comment]
@chungy - -nograbmouse is useful for the case I described above: there are situations like debugging where it it's useful to be able to disable it.

@haleyjd - that's fine then. I'm not planning on removing either of those. The ones I propose removing are -grabmouse; -novert; -nonovert. If nobody has a good use case for these then I'll go ahead and do that.

**Comment by fx02** [comment]
I approve ;)

**Comment by fragglet** [comment]
Fixed.
