### ISSUE TITLE
First dot flashes with -devparm

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#374]
Using -devparm, the first dot always flashes when the game runs smoothly. In vanilla, it doesn't blink. It still happens when running Chocolate-Doom on a Pentium 3 (300Mhz). When the framerate decreases, the farthest dot to the right also seems to be affected by this problem.

**Comment by Super6-4** [comment]
According to the Doom Wiki:
http://doomwiki.org/wiki/Uncapped_framerate

MS-DOS Doom had its render loop limited to 35 FPS because of vertical synchronization. This vertical synchronization was not present in Linux Doom, and it effectively allowed for an uncapped framerate where a scene could be rendered multiple times in a row.

I assume Chocolate Doom has been developed from the Linux source, so I believe this would be correct behavior for Linux Doom, but not correct behavior for MS-DOS Doom.

**Comment by AXDOOMER** [comment]
Vertical synchronization in MS-DOS: First thing I think about when I read vertical synchronization is Vsync in OpenGL. Google doesn't return results that are interesting. This post on Doomworld may give a better explanation: http://www.doomworld.com/vb/post/1340410. I_WaitVBL is gone, but if Chocolate-Doom redrew the screen multiple times, with doesn't it use more CPU than what it's currently using?
