### ISSUE TITLE
Extended demo support for Heretic and Hexen

### ISSUE THREAD

**Issue by plumsinus** [chocolate-doom/chocolate-doom#432]
In the near future, I'd like to attempt to add support for extended demos to Crispy Heretic and Crispy Hexen. Is this something that you think fits into Chocolate Heretic/Hexen? There is some precedent: Chocolate Doom already supports -longtics, and there are DOS-based patches to improve demo support in vanilla Heretic (vv's Heretic hack) and Hexen (entryway's Hexen+ patch/exe). Extended demos with Crispy/Chocolate would be compatible with those two patches.

Strife is another problem altogether; it seems that dialog choices aren't recorded in Strife demos. I'm content to leave it be for the time being at least.

The changes to demo recording/playback I want to implement include:
* Fix mouse turning while recording demos (unsure if this is still a problem in Chocolate actually).
* Support `-longtics` switch.
* Support multi-level demos. Multi-level demos still play back with vanilla binaries, they just quit when the player gets to the first exit.
* `-maxdemo` support and/or unlimited demo length support.
* Proper `-timedemo` support (unsure if this needs fixing).
* Allow the viewer to press tab to view the automap while a demo is playing.

Please let me know if you think any of these are acceptable for Chocolate.

**Comment by chungy** [comment]
> Strife is another problem altogether; it seems that dialog choices aren't recorded in Strife demos. I'm content to leave it be for the time being at least.

I asked @haleyjd about this on IRC a few days ago. He told me that properly supporting the dialogs in Strife demos would require rewriting and reworking the entire system to work with gametics, which they presently do not. It's a problem that would severely break vanilla compatibility and best left to some downstream port. It's a shame, it makes recording meaningful demos of Strife in vanilla/chocolate is pretty much impossible. ZDoom might have its rare moment of shining here, it supports recording Strife demos with the dialogs.

@plumsinus, if you're still actively seeking to fix these kinds of things, perhaps modifying Strife: Veteran Edition for these goals would be worthy.

**Comment by CapnClever** [comment]
> > Fix mouse turning while recording demos (unsure if this is still a problem in Chocolate actually).

> What's this?

I recently looked into this problem: it boils down to Heretic/Hexen lacking code that correctly manages shorttic turning resolution. See `/src/doom/g_game.c`, function `G_BuildTiccmd()`: it's in the conditional block `if (lowres_turn)`.

This affects not just mouse, but all turning: when recording a demo you'll turn right (via keyboard) faster than normal and turn left slower than normal. I think it's because the bitshift equates to a truncation when `angleturn` is converted to a shorttic, when it instead ought to be "rounded" (which is what the aforementioned conditional block takes care of).

**Comment by AXDOOMER** [comment]
> you'll turn right (via keyboard) faster than normal and turn left slower than normal.

Isn't this a vanilla bug?

**Comment by CapnClever** [comment]
Yes, the turning differences are vanilla behavior: I was explaining said behavior as it wasn't adequately described in the original request. That behavior negatively impacts most people who want to record demos (if you've tried it out you know why) so it could fit in the port as a reasonable improvement.

Funny you should ask, though. I knew how Heretic and Hexen were behaving and how I wanted them to behave, but I hadn't yet verified the Doom behavior. As Chocolate is about preserving vanilla whenever it's reasonable to do so, if we want the other games to be "fixed" then I should confirm "this is what it would be doing if we suppose it *was* fixed". Turns out there's a small inconsistency between vanilla and Chocolate regarding that! I'm going to write it up as a separate issue since it's not on-topic.

**Comment by CapnClever** [comment]
Heretic/Hexen stop their demos whenever a player is meant to respawn (see `G_DoReborn()`), in addition to whenever a player exits a level (see `G_DoCompleted()`). Because of this, it probably makes sense to combine both cases into a single parameter, in which case "-multilevel" isn't adequate enough to describe the feature. Any ideas? I've been considering a few:

* -demoextend / -extenddemo
* -demomulti
* -demofull
* -finishdemo

Keep in mind these apply both to the recording and playback (i.e., can't record a demo beyond a single life/level in vanilla, can't play back a demo with multiple spawns/exits even for such demos that exist). Alternatively we could just have two separate parameters, like "-multilevel" and "-multispawn".

**Comment by CapnClever** [comment]
Got some work done towards implementing these as per the OP's suggestions. In summary:

* `-maxdemo` support is added: didn't include unlimited because that included setup changes, and I figured it would be more sensible to implement the compatibility section all at once.
* `-timedemo` was fixed to count realtics starting from the beginning of playback rather than the start of the map. It didn't matter before because you couldn't play back demos with more than one level anyway.
* `-longtics` and corresponding "lowres_turn" compatibility was added. This also fixed up network game consistency problems when some players record demos and other don't.
* New command `-demoextend` allows a demo to continue after a level exit or after a player respawn. Additionally, in Hexen, the `demorecording` and `demoplayback` were constantly reset whenever loading a new map (via `G_InitNew()`) so I coded a little extra work to prevent those from resetting.
* New command `-shortticfix` smooths out the mouse when recording with lowres turning, equivalent to Doom's handling.

I tried to come up with suitable names for the new commands but additional perspectives would help.

**Comment by haleyjd** [comment]
All seems very sensible to me.

**Comment by fragglet** [comment]
Can you describe in a bit more detail what `-shortticfix` is for?

**Comment by fragglet** [comment]
EDIT: Never mind.
