### ISSUE TITLE
Not working with TiMidity++ on Linux

### ISSUE THREAD

**Issue by Xylemon** [chocolate-doom/chocolate-doom#525]
I desire to use Chocolate Doom under my Linux machine with my SC-55 soundfont using Timidity++, however it seems that despite telling Chocolate Doom where my Timidity config file, it refuses to play any music at all! I am totally at a loss here, do you any have any idea what could be the culprit?

Some specs: Chocolate Doom 2.1.0 on Slackware Linux 14.1 64-bit (Kernel 3.10.17) with Open Sound System Build 2011, and  TiMidity++ 2.14.0. Any help is greatly appreciated.

**Comment by fragglet** [comment]
Can you post the contents of your timidity.cfg? Thanks

**Comment by Xylemon** [comment]
Sure:

# This is the default configuration file for TiMidity++.
# See timidity.cfg(5) for details.

soundfont /home/<username>/Music/Soundfont/Roland_SC-55.sf2
#soundfont /home/<username>/Music/Soundfont/MagicSFver2.sf2
#soundfont /home/<username>/Music/Soundfont/SC-55.sf2

#trysource /etc/timidity/crude.cfg
#trysource /etc/timidity/freepats.cfg
#trysource /etc/timidity/eawpats.cfg
#trysource /etc/timidity/fluid.cfg

**Comment by fragglet** [comment]
Problem is that you're using an SF2 sound font. Chocolate Doom uses the SDL_mixer library for music playback, which has its own internal version of Timidity. Unfortunately this version of Timidity is quite old and doesn't support SF2 sound fonts. I think it's possible to recompile Timidity to use the external (installed) version of Timidity rather than its own internal version. If you're feeling daring you might try that.

Anyway, unfortunately this isn't a Chocolate Doom issue. Sorry I can't do more to help.

**Comment by Xylemon** [comment]
Ah I see, thanks for the help.

**Comment by fabiangreffrath** [comment]
> Unfortunately this version of Timidity is quite old and doesn't support SF2 sound fonts. I think it's possible to recompile Timidity to use the external (installed) version of Timidity rather than its own internal version.

As an aside, it is also possible to build SDL_mixer using fluidsynth which supports SF2 fonts natively. This is how it should be done on Linux distros.
