### ISSUE TITLE
Hexen v1.0: crashes at end of hub

### ISSUE THREAD

**Issue by CapnClever** [chocolate-doom/chocolate-doom#537]
reported on chocolate-hexen release version 2.1.0

Attempting to exit into a new hub (e.g., Seven Portals, Hypostyle) or finish the game causes Chocolate Hexen to crash with the following message:

W_GetNumForName: clus1msg not found!

For Hypostyle it's "clus2msg": the exact variable name changes depending on the intermission screen that's supposed to follow. HEXEN.EXE v1.0 shows no sign of this crash in DOSBox.

I have the v1.0 CD version of Hexen, so if you need any files for debugging purpose, please let me know.

**Comment by fragglet** [comment]
This probably boils down to "Chocolate Hexen only works with the v1.1 IWAD" but with @fabiangreffrath's recent tweaks to support the demo IWAD I wonder if this bug is now obsolete.

We should retest to see if this is still a problem on HEAD.

**Comment by fabiangreffrath** [comment]
I am not sure if my demo-related changes will help here. But we could check wii-doom sources for further changes that are necessary to run Hexen 1.0 -- provided we really want to start supporting obsolete game data versions.

**Comment by fabiangreffrath** [comment]
It appears that the intermission texts aka cluster messages are stored as lumps inside the Hexen 1.1 IWAD whereas they are stored in the executable in Hexen 1.0.

This is in src/hexen/in_lude.c:
```
static char *ClusMsgLumpNames[] = {
    "clus1msg",
    "clus2msg",
    "clus3msg",
    "clus4msg",
    "clus5msg"
};
```

**Comment by fragglet** [comment]
That's kind of problematic if the text wasn't included in the GPL release. Any chance that it was left in a header file, unused?

**Comment by fabiangreffrath** [comment]
Nope. :(

**Comment by haleyjd** [comment]
If we're that concerned over some strings, then, consider that a legal owner of Hexen 1.0 must have the EXE file as well. Then, require hexen.exe to exist on the same path as hexen.wad and fread the strings from it out of their known offsets. A lot of ado for some text strings though.

**Comment by fabiangreffrath** [comment]
We could just add some dummy texts, like "You are playing Version 1.0 of Hexen. Please consider upgrading to version 1.1 following the guide ...". This would be frustrating, sure, but not as much as a crashing game.

**Comment by haleyjd** [comment]
Inability to do a pure, proper, 100% accurate emulation is precisely why we dismissed any possibility of supporting the Strife demo version; it would have required either a totally separate codebase (/src/strife-demo) or would have completely sacrificed the choco philosophy of minimal code modification. If the best effort that can be done is to do nothing, I'd suggest that adding this to begin with was misguided.

**Comment by bb010g** [comment]
What about some sort of config file that would be preset with dummy texts, but could be filled with the proper texts, possibly automatically extracted from the executable?

**Comment by fragglet** [comment]
Nah, too complicated a solution. 

I'd potentially accept replacing the story text with a message instructing the user that their IWAD is out of date and they should upgrade to v1.1 (and some warnings shown on startup as well). This is kind of comparable to the BFG Edition situation, where it's worth making some minimal changes that at least allow the game to be played.

**Comment by fragglet** [comment]
Lumps that are in the Hexen v1.1 IWAD, but not in v1.0:

    TRANTBL9       256  Lump of raw data
    TRANTBLA       256  Lump of raw data
    TRANTBLB       256  Lump of raw data
    TRANTBLC       256  Lump of raw data
    TRANTBLD       256  Lump of raw data
    TRANTBLE       256  Lump of raw data
    TRANTBLF       256  Lump of raw data
    TRANTBLG       256  Lump of raw data
    TRANTBLH       256  Lump of raw data
    TRANTBLI       256  Lump of raw data
    TRANTBLJ       256  Lump of raw data
    TRANTBLK       256  Lump of raw data
    TALLYTOP      6132  Graphic
    TALLYLFT      4944  Graphic
    CLUS1MSG       569  Lump of raw data
    CLUS2MSG       626  Lump of raw data
    CLUS3MSG       623  Lump of raw data
    CLUS4MSG       324  Lump of raw data
    WIN1MSG        344  Graphic
    WIN2MSG        399  Graphic
    WIN3MSG        123  Graphic
    LIFEGMF5      1384  Graphic
    LIFEGMF6      1384  Graphic
    LIFEGMF7      1384  Graphic
    LIFEGMF8      1384  Graphic
    LIFEGMC5      1384  Graphic
    LIFEGMC6      1384  Graphic
    LIFEGMC7      1384  Graphic
    LIFEGMC8      1384  Graphic
    LIFEGMM5      1384  Graphic
    LIFEGMM6      1384  Graphic
    LIFEGMM7      1384  Graphic
    LIFEGMM8      1384  Graphic

Each of these can possibly be another bug waiting to be discovered. This might be too much to deal with.

**Comment by fragglet** [comment]
Added a warning message; we won't be supporting v1.0 for the time being.

**Comment by fabiangreffrath** [comment]
It is quite obvious that Hexen 1.0 did only support 4 maxplayers. This is a case we already support by supporting to run the Demo version and this also makes the missing of most of the lumps pretty harmless.

For example, the game needs `3 * (maxplayers - 1)` TRANTBLx lumps in R_InitTranslationTables(). That's 9 lumps for (maxplayers == 4), the additional 12 lumps required for (maxplayers == 8) are only in the Hexen 1.1 IWAD.

Same for the LIFEGEM lumps. We need `maxplayers * class + 1` of them, so the Hexen 1.1 IWAD really only ships the additional ones because it has raised maxplayers to 8.

What's left is TALLYTOP/TALLYLFT, which is needed in DrDeathTally() which in turn is only called by IN_Drawer() if (gametype != SINGLE). I have no idea, yet, what this is.

The remaining 7 lumps are the intermission and victory text screens, and I really think we could replace them with a dummy text. 

Maybe something along these lines:
"You are playing with the Hexen 1.0 game data file.

Usually, an intermission text would appear here to guide you through the narration of the game. However, this text is missing in the version of the game data that you are currently playing.
In order to enjoy the full Hexen gaming experience, please update you game data to the 1.1 version.

 - The Chocolate Hexen Team"

I know this is really bending the Choco philosophy, but Hexen is a special case. As far as I know, it was only sold as Version 1.0 on CD-ROM. So, anybody who has bought the game but never bothered to update it with files downloaded from the internet still has this version. It is really *the* original version of Hexen and it would be a pitty to not support it.

**Comment by fabiangreffrath** [comment]
>Inability to do a pure, proper, 100% accurate emulation [...]

While I generally agree with you, we should probably also ask ourselves if this is meant to be a general-purpose port of if it's just here to fill a special niche. If we do not support the version of Hexen that was sold in stores because of the text I quoted, we might run into problems.

**Comment by fragglet** [comment]
I appreciate the sentiment, but how many people are even using the store CD versions nowadays? I'd expect most people to be either buying the Steam version or getting second hand copies off eBay. There aren't many other channels for getting Hexen legitimately. In the former case, I believe (correct me if I'm wrong?) that the version on Steam should have the v1.1 IWAD. In the latter case we're talking about techies or retro game collectors who shouldn't have any trouble patching their install.

The other use case is people who find their old Hexen CD in the back of their closet and want to play it again for nostalgia's sake. Again these should necessarily be people who once used DOS and should be capable of running upgrade patches. We might provide some better instructions on the wiki, as the steps to run it aren't necessarily straightforward.

**Comment by chungy** [comment]
All games on Steam are the last versions for DOS, with the exception of _Deathkings of the Dark Citadel_ (`hexdd.wad`). Even in that case, I don't think it actually presents a compatibility issue.
