### ISSUE TITLE
Add back the Doom reload hack

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#539]
The doom reload hack was removed from w_wad.c way back in d190b596c56639471732. However, after [writing an article on the wiki about it](http://doomwiki.org/wiki/Reload_hack) and [making a video demonstrating it](https://www.youtube.com/watch?v=zQqwPeYh8mk) I kind of regret that decision and want to add it back again. It's the kind of obscure feature that Chocolate Doom ought to support, and I had some comments on the video from people who want to try it out / use it for development.

**Comment by fragglet** [comment]
Looks like the Heretic/Hexen versions of w_wad.c didn't include the reload hack, I don't know if Strife did. It should just be a matter of calling or not calling W_Reload() as appropriate.

Internals of this might be slightly complicated as Chocolate Doom's w_wad.c works a bit differently. Need to use the w_file interface and regenerate the lump hash table on reload.

**Comment by sneakernets** [comment]
I can see the BTSX project benefitting greatly from this. Glad to hear this is on the table.

**Comment by haleyjd** [comment]
The reload and -wart mechanisms are entirely intact in Strife; checked W_AddFile, W_Reload, and D_DoomMain. It would even appear that Rogue may have even used the feature themselves, as the paths referenced by -wart have been changed to load from either ~f:/st/data/map0%i.wad or ~f:/st/data/map%i.wad depending on the map number referenced (instead of using %02i...) Can post pics of the code if you're interested.

**Comment by fragglet** [comment]
Feature now restored. @haleyjd - thanks for confirming Strife support for the hack; I included the W_Reload() call in strife/p_setup.c.
