### ISSUE TITLE
Game quits when I pull up the map in multiplayer

### ISSUE THREAD

**Issue by Marscaleb** [chocolate-doom/chocolate-doom#571]
I apologize, I posted this in the wrong place, but can't find an option to delete this bug report.

**Comment by fragglet** [comment]
Out of interest how did you resolve the problem?

**Comment by fabiangreffrath** [comment]
It was a simple bug introduced by my Automap Rotation patch:
https://github.com/fabiangreffrath/crispy-doom/commit/7a39c3bfeb716178773681e81fc20cce91a1f57e

**Comment by haleyjd** [comment]
Respecting that this was resolved, I'm still going to again strongly suggest disabling the SDL parachute so that users can give a more descriptive response than "the program just exited." The parachute is going away in SDL 2.0 anyway, since all it ever did was eat exceptions that are supposed to be caught and reported by the system. Also interferes with the ability to attach a debugger on Windows, at the least.

**Comment by fragglet** [comment]
@haleyjd a fair point, but we're already moving to SDL2 anyway with sdl2-branch, so let's perhaps just consider that the solution to SDL parachute problems.
