### ISSUE TITLE
Framerate issues (Windows GDI)

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#662]
See: https://www.doomworld.com/vb/post/1551846

Video: https://youtu.be/nXkQwQ14qZo?t=37s

**Comment by fragglet** [comment]
Still not sure I understand what the issue is here. Note that the fact that Fraps says 35fps instead of 60fps does not mean it is worse: Chocolate Doom only ever got 60fps because it was mistakenly rendering the screen twice.

It may be that there's some other (input-related?) issue that the double-rendering bug was masking.

Can you try to describe the "feeling" behind what seems to be wrong in as much detail as possible? "Lag" is ambiguous and can have many different interpretations.

**Comment by AXDOOMER** [comment]
It's not an input lag, the issue is with the rendering. You can see it in my video, the first part is the older version, which draws the screen smoothly. In the second part, after 37 seconds, is the same demo playing in a more recent version of Chocolate-Doom. It looks like frame skipping or like if some frames hang before the next is drawn. I have no idea if it can be reproduced on other computers, I have only tried on my laptop which has a screen that has two refresh rates (60hz and 40hz).

**Comment by AXDOOMER** [comment]
This bug doesn't occur with DirectX, only Windows GDI. 

I'll close it right now because Chocolate-Doom is moving to SDL2 with hardware scaling and it only happened with GDI, it won't be a problem anymore. Chocolate-Doom v2 will be obsolete soon.

**Comment by bencun** [comment]
I see that the issue has been closed but I'm experiencing this uncomfortable stutter right now. I've never used Choc Doom before, so I went straight for the newest version, downloaded from the official website. Whatever I do in the config file the game simply doesn't look or play smooth and the video from the initial comment shows very well how bad the experience is.
I've launched vanilla Doom immediately afterwards in DOSBox in order to check my sanity and the difference is obvious, the DOS version is super-smooth compared to Chocolate.
Windows 10 Pro, i7 6700, RX480 etc.

**Comment by AXDOOMER** [comment]
For Chocolate-Doom 2.x.x, you have to set the `video_driver` in  chocolate-doom.cfg to `directx`. 

The newer Chocolate-Doom 3 uses OpenGL.

**Comment by bencun** [comment]
I did try changing `video_driver` to `directx` before posting my comment but that resulted in game running in the foreground and it's window being completely transparent (the music was playing and the keyboard input was working) so I had to close the game by Win+Tabbing and clicking on close button.
Nonetheless, it's great to see that v3 has fixed this issue.
