### ISSUE TITLE
Blue disk is drawn under the numbers in the lower right and is modified during the screen melt

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#668]
The blue disk may be drawn under the yellow numbers. I've seen it sometimes. It happens very rarely. Also, the icon is affected by the screen melt. I believe vanilla didn't have such issues. 

![vlcsnap-2016-02-08-21h50m35s85](https://cloud.githubusercontent.com/assets/6194072/12906442/49230d54-ceae-11e5-935a-d60b42d195e5.png)
(VLC got the colors wrong)

**Comment by jmtd** [comment]
I'm fairly sure that the disk *did* melt with the rest of the screen, if it happened to be loaded at the time the wipe starts, in vanilla. I think that it is probably less likely to be present on the screen in vanilla, because we artificially hold the disk icon for a full tic (or did, maybe we tweaked that since it was first written). So the difference is in the hold. But because we don't do the same pageflipping that vanilla did, and because disk loads are going to be much faster than on a '94 era PC, I don't think we can expect to get the behaviour to match perfectly.

As for overlapping the numbers, that sounds like a bug in the save/restore code for the region where the blue disk writes.

**Comment by AXDOOMER** [comment]
Did you look at this?
https://github.com/id-Software/DOOM/blob/master/linuxdoom-1.10/m_random.c#L71
https://github.com/chocolate-doom/chocolate-doom/blob/master/src/doom/m_random.c#L73

Is Chocolate-Doom faithful to Vanilla Doom or it's Linux Doom that does the correct behavior?

**Comment by fragglet** [comment]
> As for overlapping the numbers, that sounds like a bug in the save/restore code for the region where the blue disk writes.

I noticed that one of the changes on the diskicon branch was to get rid of the background save/restore code for the disk icon and make the game code redraw the disk icon itself (see 7a29515569b65 for one part of its implementation). I never quite understood the rationale for doing this since it's a far more fragile mechanism and I was worried we'd end up with bugs like these.

Would it make sense to revert this change?

**Comment by fabiangreffrath** [comment]
Rationale: It happened that the disk background was backed up at the end of an intermission screen, the disk patch was drawn to the framebuffer, the screen melted and then the background was restored on the player view, i.e. on the status bar.

**Comment by fragglet** [comment]
Seems like the obvious solution should be that the disk drawing and restore happens entirely inside I_FinishUpdate() - is that not how it worked?

**Comment by fabiangreffrath** [comment]
Honestly, I don't remember anymore. Gowever, if you want to give it another try with a different approach, I am all for it.

**Comment by fragglet** [comment]
I encountered this bug myself while playing last night. I want to revert the redraw changes to the game code (7a29515569b) and change to doing save/restore inside I_FinishUpdate, as suggested.

**Comment by jmtd** [comment]
Fraggle, to be clear, did you see either a) the disk on the wipe or b) the disk drawn incorrectly underneath the numbers? (or c) both I suppose)

wrt a), are we 100% sure that this was impossible in vanilla?

**Comment by nukeykt** [comment]
@jmtd it is impossible in vanilla doom/strife, since vanilla draws disk icon directly to graphic card memory, not to video buffer like chocolate. Original vanilla code: https://github.com/OpenSourcedGames/Heretic/blob/master/Heretic%20Source/I_IBM.C#L1932

**Comment by nukeykt** [comment]
Check out of my implementation of disk icon in hom-branch: https://github.com/nukeykt/chocolate-doom-beta-opl/tree/hom-branch

**Comment by jmtd** [comment]
OK, I gave the code a quick look and have some comments (not written down), but I suggest we leave this issue for now until the HOM branch issue is resolved, since the implementation depends so much on it. (And so much on sdl2-branch underneath it all. We really need to get that finished :))

**Comment by AXDOOMER** [comment]
Got a screenshot:
![doom83](https://cloud.githubusercontent.com/assets/6194072/14412346/c0977676-ff2e-11e5-804b-3e969dcf28ee.png)
The disk stayed there until I removed the status bar to force an update.

**Comment by chungy** [comment]
@jmtd @fabiangreffrath 
A 2.3.0 release is imminent and this feature still seems partially broken. Can it be fixed in a short time, or should the feature be reverted for the release?

**Comment by fragglet** [comment]
Looking into fixing this now.
