### ISSUE TITLE
Network compatibility via Dosbox

### ISSUE THREAD

**Issue by XCOPY-** [chocolate-doom/chocolate-doom#685]
Maybe Chocolate-doom could be network compatible with Vanilla Doom via Dosbox, with [xttl's IPXSETUP](https://www.doomworld.com/vb/post/1577690)?

**Comment by linguica** [comment]
Isn't IPX support considered out of bounds for the project? https://github.com/chocolate-doom/chocolate-doom/blob/master/PHILOSOPHY#L98

**Comment by fragglet** [comment]
If you'd asked me a few years ago I would have ruled it out of scope and closed the bug. But I'm actually vaguely open minded to the idea. I will concede that it's probably unlikely to happen just because it will be a lot of work.

I've had a couple of ideas here:

1. Make every Chocolate Doom server into a DOSbox IPX-over-UDP server. You could then "ipxnet connect" to a Chocolate Doom server from within DOSbox and run ipxsetup. The server would detect Vanilla clients and set appropriate options to make Chocolate clients play the game properly.

2. I have this really crazy idea to implement a DOS "proxy" for Chocolate Doom. There are several command line options which communicate with external drivers via shared memory: -net (ipxsetup/sersetup), -statcopy and -control. In theory, these could be made to run a "dummy" version of doom2.exe that set up a serial port as a fake modem. Chocolate Doom could then "dial into" the DOSbox instance to talk to the proxy binary. Memory copies are routed through the fake serial port, allowing Chocolate Doom to use DOS network drivers, statistics drivers and external control drivers.

Either approach requires reimplementing the Vanilla network protocols, which have been replaced at this stage.

**Comment by Danfun64** [comment]
I think that either the new netcode should be kept, as it's more optimized for internet play, or when and if the old netcode is reimplemented, it should be partially be rewritten so it's optimized for internet play.

If you're doing the former, you should have three options:

Netcode: Old (IPX), Old (DOSBOX IPXNET), New (TCP/IP)

**Comment by fragglet** [comment]
Native IPX support has never been seriously considered, only DOSbox-compatible IPX. Any option like you suggest should be unnecessary.

**Comment by Danfun64** [comment]
I wonder when and if somebody is ever going to port IPXNET to Dos and Win9x. Shouldn't be impossible, since Kali was once a thing. I'm just a little surprised nobody seems to have even attempted it after all these years...

**Comment by PorscheMonty** [comment]
A different take; would implementing anything IPX make CD capable of replicating vanilla's networking behavior more accurately, meanings bugs, limitations and everything else? If not, then i don't personally see the point.

**Comment by chungy** [comment]
No, and native IPX has not been supported by any major operating system for many years. Restoring such support would require kernel-mode drivers, and that's far from any reasonable expectation for Chocolate Doom. DOSBox emulates it by encapsulating it over IP/UDP.

**Comment by fragglet** [comment]
I never updated this bug, but the vanilla-net branch now has implementations of the IPX and serial protocols, which should satisfy the original feature request:

https://www.chocolate-doom.org/wiki/index.php/Vanilla-net
