### ISSUE TITLE
In the SDL2-port I have to press "Z" to confirm the quit dialog

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#712]
First, I should mention that I have a German keyboard which has "Y" and "Z" switched compared to an US-American keyboard.

Whenever I quit the game, I have to press "Z" on my keyboard to confirm the quit dialog. This is regardless of the "Use native keyboard mapping" feature being enabled or not.

In the SDL1.x port, I can always confirm the dialog by pressing "Y" -- again regardless of the "Use native keyboard mapping" feature being enabled or not.

However, when I play a `-solo-net` game, this feature does make a difference when I type a message by pressing "T", as it switches "Y" and "Z" on my keyboard between native and US-American layout.

 - Fabian

**Comment by fabiangreffrath** [comment]
Sorry for the short initial report. My cat decided to send the message while I was typing...

**Comment by chungy** [comment]
> In the SDL1.x port, I can always confirm the dialog by pressing "Y" -- again regardless of the "Use native keyboard mapping" feature being enabled or not.

This sounds like a bug in both versions.

**Comment by fabiangreffrath** [comment]
> This sounds like a bug in both versions.

Yep, strange somehow. Sounds like a `data1` and `data2` mix-up, but I am not sure.

**Comment by fragglet** [comment]
I looked into this and it's kind of tricky to fix. The problem here is that we added reconfigurable key bindings for the menu: you can go into the setup tool and change the keys you have to press for 'Y', 'N', etc. to answer the questions the menu gives you. Key bindings are done on scancode (data1, ie. physical key) rather than keycode (data2, depends on keyboard layout). So I think we have a situation where we need to choose between either taking keyboard layout into consideration or having rebindable key bindings.

**Comment by fx02** [comment]
It should default to US keyboard and then let user rebind keys to whatever he wants to.

**Comment by jmtd** [comment]
Kind-of related but I think we should be a bit lax about confirming menu dialogs in general. I think <fire>, via mouse or joypad, should trigger enter menu and also 'Y' for "quit?" etc., so that it's possible to launch, play and quit the game entirely with a joypad (e.g. in an environment like a retropie).

**Comment by jmtd** [comment]
Right now (assuming #745 meets approval) this is the last bug in the SDL2 milestone \o/

**Comment by fabiangreffrath** [comment]
Strictly speaking, this shouldn't actually be an issue at all anymore. I wasn't aware of the fact (well, I was, but somehow forgot about it) that the menu confirm and abort keys were freely configurable in Choco. The quit dialog, however, merely asks you to press either Y or N. I found that confusing, because other dialogues requiring text input, e.g. the in-game chat, had these keys left untouched. Please close this if you agree that "menu keys are configurable" if the cure to this issue.

**Comment by jmtd** [comment]
I think I agree @fabiangreffrath , thanks!
