### ISSUE TITLE
In the SDL2-port, in the setup tool, remove the resolution selection if "Fullscreen" is enabled

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#717]
This dialog is misleading:

![bildschirmfoto vom 2016-05-19 18-31-04](https://cloud.githubusercontent.com/assets/6449237/15406248/fe90cf5e-1e05-11e6-91fd-c7a03c0fb241.png)

People tend to think that if "Fullscreen" is enabled the screen will be changed to the resolution given in the "Window size" box, although the word "Window" should already suggest differently. IMHO, this part of the dialog has to go if the "Fullscreen" option is enabled.

**Comment by haleyjd** [comment]
Is true fullscreen still an option? I'll note that many people had trouble running Noctropolis as a "desktop-sized window"; this is a video driver issue with OpenGL stuff unfortunately.

**Comment by fragglet** [comment]
The basic rationale is (and I agree with it): most people have LCD monitors nowadays. We should therefore just run at the native screen resolution. Using the configured desktop resolution should achieve this on any properly configured computer and also avoids switching modes.

I believe all the potential reasons for not doing this either do not exist or have now been eliminated: Chocolate Doom renders the same 320x200 screen regardless of detail (so a screen mode control does nothing useful), and with hardware scaling we can now scale to any resolution without using CPU (previously, scaling to large resolutions in software could be slow on some machines).

I'm curious to hear about problems with running fullscreen, especially if they're driver-related since we made the decision that from 3.0 onwards we're only ever going to do hardware scaling. Maybe there are workarounds of some kind that we can provide.

**Comment by fragglet** [comment]
Oh and to respond to the original comment: I suggest we change the UI for the display window as suggested. Move the fullscreen control to the top, and make the window size control appear/disappear when fullscreen is disabled/enabled.

Maybe we can add a small label below the fullscreen control: "[can be toggled in-game with alt+enter]".

Side issue: I assume by default when fullscreen=true we're calling SDL_CreateWindow with w=0, h=0, flags=SDL_WINDOW_FULLSCREEN_DESKTOP. It would be nice to have a couple of extra config file variables (`fullscreen_width`, `fullscreen_height`), defaulting to zero, and if they're non-zero we use SDL_WINDOW_FULLSCREEN instead. We needn't expose it in the setup tool but it would be there in the config file if someone really needs it.

**Comment by fragglet** [comment]
Fixed.
