### ISSUE TITLE
Crashes on YELLOW.WAD

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#72]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/72/) on Sourceforge by [never_again](https://sourceforge.net/u/never_again/profile/), 2010-06-25 15:46:58:

Crashes in several places on YELLOW.WAD. The WAD is not on \idgames, so I attach it here. Two short demos are included. Both recorded in vanilla. The first is about 37 seconds long but crashes only four seconds into the level with Chocolate DOOM. The second is ~ 41 seconds, crashes on 27th.
Yes, it's a buggy level, but vanilla has no problems with it, the level can be completed with 100% kills.

**Comment by Super6-4** [comment]
Oh boy is this issue old (still crashes though).

**(Quick) Debugging**

Popping this map open in GZDoomBuilder, here is what it says:
`1120 Vertices, 1309 Linedefs, 2081 Sidedefs, 241 Sectors, 881 Things`

I did not check the number of Things loaded. The only discrepancy when Chocolate loads this level is the number of vertices. Chocolate loads 1421 vertices.

**Comment by fabiangreffrath** [comment]
It crashes in `PIT_AddLineIntercepts()` in the following line:
```
s1 = P_PointOnDivlineSide (ld->v1->x, ld->v1->y, &trace);
```
Both `ld->v1` and `ld->v2` are `NULL` pointers and dereferencing the former causes the segmentation fault. 

Note that the linedef in question, `ld`, is line number 65279 according to gcc, so there seems to be an error already in the subsectors lump of that map (or in another critical part of the map layout).

**Comment by fabiangreffrath** [comment]
Nope, it's the blockmap lump. PrBoom+ reports the following
```
P_VerifyBlockMap: index >= numlines
P_LoadBlockMap: erroneous BLOCKMAP lump may cause crashes.
P_LoadBlockMap: use "-blockmap" command line switch for rebuilding
```
and crashed shortly after. Running the map with the `-blockmap` parameter allows to play the demo until the end.

**Comment by Super6-4** [comment]
> The WAD is not on \idgames

So is it from one of those shovelware WAD CDs? If we wanted to investigate this further, we would have to find the original source to rule out corruption on the user's end (e.x. scratched CD when copying YELLOW to disk).

But, given the general low-quality of the WADs on those disks, I wouldn't be surprised if it came like that. They probably fired it up in Doom, it ran, and they shipped it.

Overall, I would say this is an *unfixable* issue. Regenerating the blockmap would potentially have the demo playing with different collision than it was recorded with.

**Comment by haleyjd** [comment]
There are a surprising number of WADs with this issue; I believe they might originate with some particular tool that generated bad blockmaps. What is suspicious about a number of them (such as some copies of AMADEUS.WAD) is that only a single bit is flipped making the indices into large numbers versus their correct values.

**Comment by tpoppins** [comment]
I am the submitter of the original ticket on SF and can confirm that this is another case of a corrupted WAD. The source is the same as with [#1254](https://github.com/chocolate-doom/chocolate-doom/issues/1254#issuecomment-1316396929) - the "Death Match 7000" 2xCD set. AMADEUS.WAD, mentioned by Quasar, is yet another example; and that bad copy even made it into /idgames.

A couple of months ago I tracked down the original source for YELLOW.WAD. The map turned out to be an entry in the PC Zone's WAD Competition and is thus included on [the cover CD](https://archive.org/details/pc-zone-december-1994-disc) of the mag's Dec 1994 issue. The CRC-32 of the original is F5A0048D. The CRC-32 for the bad copy on DM7000 (also included in the ZIP at the start of this thread) is 8DC5EAB6. The difference between the two is once again in BLOCKMAP only, and is exactly the same as in the case of DWHEEL,

This issue can be closed as invalid.
