### ISSUE TITLE
SDL2: mouse wheel handling is broken

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#722]
SDL2 changed how mouse wheel input works.

**Comment by jmtd** [comment]
Ok taking a brief look this BST-evening

**Comment by jmtd** [comment]
work in progress pushed to [sdl2-mousewheel](https://github.com/chocolate-doom/chocolate-doom/tree/sdl2-mousewheel) branch.

I think the setup side of things is fine but the in-game wheel/button events aren't firing properly. I think
it's something to do with the doom event side of things rather than the SDL side. I need to read a bit more about how that works to make further progress.

I pushed to a branch here rather than in my fork in case anyone wants to pick up my work in  progress, they can push more patches to that branch. I didn't open a PR because it's not working so not merge-worthy yet. Is this a sensible workflow for this situation?

**Comment by jmtd** [comment]
Oh yeah I did try having MapMouseWheelToButtons call UpdateMouseButtonState instead of doing the event_t manipulation itself, but then you have to do some arithmetic since the latter expects SDL-indexed buttons and corrects for them, which made things pretty illegible.

**Comment by jmtd** [comment]
Just tried a hack where instead of genering doom event_t I used SDL_PushEvent to synthesize button events instead; same results. I suspect this is something to do with the two events being in such close succession / same tic or whatever.

**Comment by jmtd** [comment]
I remember now where I've hit this before; it was when I was looking at prev/next weapon. There, I wanted to try and synthesis two '3' keystrokes to switch from pistol -> SG via SSG. I don't know if it would work, but if we could post an event to a future tic somehow (a delayed processing event queue) then in the sitaution where you have both SSG and SG and want to 'next' weapon from pistol, we'd send a '3' keystroke for this tic and queue a '3' for the next one (or a future one - not sure how long a gap you have to leave for it to work).

I think this is basically the same thing here. We need to simulate a button up event for a future tic.

**Comment by jmtd** [comment]
The simplest first take would be to have a single event_t object that you could write to in a given tic  and was moved into the events array early on, before event processing. But we would really need a queue I think.

**Comment by jmtd** [comment]
Ok on master with sdl1 the button up and down events for wheel movement arrive on the same gametic so that's not it...

**Comment by jmtd** [comment]
And binding move fwd and backwards to those presses fails to result in movement,
So there's no regression at least

**Comment by jmtd** [comment]
Ok prev next weapon work modulo skipping over weapons because you get so many press events for a little scroll. I think this works as sdl1/master does then, but there's room for improvement

**Comment by jmtd** [comment]
Ah the behaviour I noticed is already reported as  #76.
