### ISSUE TITLE
Update wiki for v3 release

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#723]
For v3 onwards we're going to use chocpkg and get rid of the old build-chocolate-doom script. We need to update the wiki to document how to use it.

**Comment by fragglet** [comment]
To clarify: I mean we need to update the build instructions on the wiki.

**Comment by fragglet** [comment]
http://www.chocolate-doom.org/wiki/index.php/User:Fraggle/Pages_to_update_for_v3

**Comment by jmtd** [comment]
How do you plan to have the content during this transitional phase: shall we update the wiki to v3 (and make it invalid for the current release); wait until the last moment to update it all; set up v3 sub-pages that can co-exist, or add v3 sub-headings on the relevant pages until release?

**Comment by chungy** [comment]
Somewhat unrelated, but I've noticed the wiki's sidebar still points to https://github.com/fragglet/chocolate-doom rather than the new home. That should be updated.

**Comment by jmtd** [comment]
This can be fixed by editing https://www.chocolate-doom.org/wiki/index.php/MediaWiki:Sidebar

but the editor needs editinterface permission (which you have if you are an administrator)

If someone could bump me to admin or just add that perm I can fix it (or similar in future)

Whilst we are talking wiki, any objections if we move to a redirect-to-HTTPS model? I just noticed the login form can post back to HTTP if you access it that way.

**Comment by jmtd** [comment]
Answering my own question about content: I think we should add a "Version 3" sub-section to pages where the content needs to differ for v3, so it co-exists with the presently-stable version. Post-release we could then either remove the non-v3 content or re-arrange pages so that "Version 2 and earlier" stuff is preserved under it's own header, if we deem that important.

**Comment by jmtd** [comment]
Just noticed that @fragglet  has already chosen an approach using sub-pages so sticking to that for consistency

**Comment by jmtd** [comment]
Sidebar is fixed; I've done most of the pages on @fragglet's TODO list.

**Comment by fragglet** [comment]
Awesome, thank you!

**Comment by twipley** [comment]
Could also be specified on the wiki, the graphical considerations as discussed along the lines of https://github.com/chocolate-doom/chocolate-doom/issues/450 ?

**Comment by fragglet** [comment]
@twipley - sorry, I don't understand what you're asking for.

**Comment by jmtd** [comment]
OK at this point I'm not sure how to proceed with updating the wiki. When should we modify the pages to reflect v3? When we cut a non-beta release of v3? In the mean time, there are mostly a bunch of /v3 sub-pages, should we link to those from their parents? (e.g. *this page describes the current stable version of chocolate-doom, v2. For information on development releases, see v3*)

Whenever we *do* move the main pages over to v3 material, I think we should copy and paste the content from the v3 sub-pages into the parents, rather than move/rename them around, so that there's a useful history for the main pages. We should probably then copy the contents of the main pages into v2 sub-pages if we want to continue to document v2 going forward.

**Comment by fragglet** [comment]
I did this update when I did the 3.0 release.
