### ISSUE TITLE
Set video_driver to "directx" and window_position to "center" in chocolate-doom.cfg by default

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#734]
I think the first one should be done for the reason of https://github.com/chocolate-doom/chocolate-doom/issues/662 and the second one for the sake of convenience :)

**Comment by fragglet** [comment]
First one won't be done; the move to SDL2 should eliminate the issue with the directx driver.

Regarding the second, the default is to do whatever the system's window manager does by default. What's special about Chocolate Doom compared to other applications that means it should always appear in the center of the screen?

**Comment by fx02** [comment]
Yeah, SDL2 fixed all video issues on modern systems. At least what I tested works now just fine on win8/8.1 and win10.

**Comment by linguica** [comment]
I think the proper comparison isn't to other arbitrary programs but to other games with widowed modes. I feel like a lot of those will auto-center their window, but maybe I'm mistaken.

**Comment by haleyjd** [comment]
The default behavior on Windows at least is seriously annoying; every subsequent execution of the program will leave it one window title bar's height lower and one window border's width to the right than the last time, and this will repeat until a certain threshold is reached whence it will move back up toward the top left corner of the screen. The first thing I have to do is alt+tab out of the game, grab the window title bar, and move it to the center. The question shouldn't be why Chocolate isn't special, but why anyone would ever want to play a game without it being in the center of their field of vision.

**Comment by AXDOOMER** [comment]
> why anyone would ever want to play a game without it being in the center of their field of vision.

The center of the screen is not necessarily the center of your field of vision. It's not the same for everybody. Assuming that the center of the screen is the center of the person's field of vision is wrong. You can change the window_position variable to center by yourself, else it will override the OS default, so if one Linux user changes the way his windows on his desktop, it will be overrided by Chocolate-Doom and his thing will not work. What's negative with applications starting in the center of the screen is that when you open a lot of them, they hide each other. 

> The first thing I have to do is alt+tab out of the game

Normally, when you press 'Escape', you should see the mouse cursor so you shouldn't have to do Alt+Tab. 

> I think the first one should be done for the reason of #662 

I don't believe the default video driver should be changed from GDI (default) to DirectX only because of https://github.com/chocolate-doom/chocolate-doom/issues/662. There are less issues in GDI mode. DirectX was previously the default and it was changed to GDI for this reason. Users who have problems should change the video driver by themselves. The framerate issue affects a minority of users.

**Comment by fragglet** [comment]
Thanks, I was hoping to provoke some discussion and this is all really good. I'm not averse to centering by default but I'm way of "special snowflake" behavior where we assume Chocolate Doom has some kind of special right to behave differently to other applications.

One thing to consider here is that most window managers are based around laying out windows in such a way that allows desktop users to run multiple concurrent applications. For example suppose you're running a word processor and a spreadsheet program - it's good to have them in separate areas of the screen to allow task switching and things like cut and paste.

For a game the same assumptions don't necessarily hold - you tend to play the game in isolation. It occupies your attention until you finish playing and quit. Sometimes there are reasons you want to switch away to another application but it's a lot less likely. That's why it's reasonable for games to default to fullscreen for example.

There are some examples of where centering the window would be annoying. If you run a "local multiplayer" game with multiple clients running on your desktop in parallel then all the windows stack on top of each other.

If we do want to make any change the default at all then I'd like to do it as part of version 3.

> I don't believe the default video driver should be changed from GDI (default) to DirectX only because of #662.

Yes, on balance I think sticking with GDI is the best thing to do, whatever problems it may have. Given this whole issue will become moot with SDL2 I don't want to dedicate any time to it.

**Comment by chungy** [comment]
I think @linguica brings up a good point. Many, if not most, games already do a centered window by default, especially such attention-grabbing games like Doom. It's not so reasonable for a Sudoku game to do it (for example), but Sudoku can also be played in between other work.

**Comment by Zodomaniac** [comment]
So finally, will the window be centered by default?

**Comment by CapnClever** [comment]
With regards to my own usage, it isn't so much that I want the default to be some particular value, rather I would like Chocolate Doom not to revert back to this default every time I use it: ideally it'd store the position in some manner. Center is better, but I don't think I'd end up moving the window any less. It also forces the window to a particular monitor, which can be equally annoying.

Heck, I didn't know either of these options were available until I read this issue (and, even if I did, understanding their usage would require trial-and-error). Perhaps the configuration file can auto-generate with some comment related to variables that don't show up in the GUI?

**Comment by haleyjd** [comment]
Forcing to a particular monitor should not be an issue under SDL 2, as it can specify on which monitor to place the window, regardless of whether it's windowed or fullscreen.

**Comment by jmtd** [comment]
> Forcing to a particular monitor should not be an issue under SDL 2, as it can specify on which monitor to place the window, regardless of whether it's windowed or fullscreen.

Unless we ask it to put it on something other than the first monitor, if the user prefers it on a different one, then they will have to move it every time they start choco. However, I don't think we should try to address this, which would mean adding preferred monitor tracking and I think that would be too complex.

**Comment by haleyjd** [comment]
I implemented it in Noctropolis and it really wasn't complicated at all, it's just another number that goes along with the width, height, and fullscreen status of the window.

**Comment by jmtd** [comment]
> I implemented it in Noctropolis and it really wasn't complicated at all, it's just another number that goes along with the width, height, and fullscreen status of the window.

So say we start saving `choco_preferred_monitor=3` or whatever in the CFG, what happens if the user plugs (and unplugs) different monitors in?

**Comment by fragglet** [comment]
We could use the display name (`SDL_GetDisplayName()`) to get a more precise fix but I don't think it's worth it. It's reasonable to assume that monitors don't move around much. If the preferred display no longer exists then place on any display and also disregard the preferred window position.

**Comment by fragglet** [comment]
I implemented display pinning but it's currently untested (I don't have a second monitor to hand)

**Comment by fragglet** [comment]
Tried with a second monitor and my code works; the only minor issue is that it only applies to the game window; ENDOOM and startup screen appear on the default display.

**Comment by jmtd** [comment]
I figured that one day we would share the same window for all those things (startup/game/endoom); what do you think of that?

**Comment by fragglet** [comment]
@jmtd - unlikely / difficult because of the module boundary separation. textscreen opens its own window for example; it's standalone.

Given that the ENDOOM and startup screens are just transient I think what we have is fine. I'm going to close this as fixed.

**Comment by vinskitakahashi** [comment]
still havent been done
