### ISSUE TITLE
SDL2: Detect and handle when no hardware acceleration exists

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#741]
I just got a CHIP (https://getchip.com/) which currently has no OpenGL drivers and so draws everything to the screen entirely in software. Chocolate Doom v2 works okayish but sdl2-branch is really slow on Mesa software GL. We should at least do something when there's no hardware acceleration - maybe something as simple as printing a message to the console.

**Comment by jmtd** [comment]
This might be challenging. I've tried and failed (so far) to set up an environment where SDL2 doesn't think it has acceleration. Even a VNC server on a linux VM resulted in supposed acceleration and (slow) rendering.

I tried getting the renderer info via SDL_GetRendererInfo, nothing useful. I read somewhere that there's a way to query the amount of vram and you get "0" for a non-accelerated situation so that's worth a shot.

**Comment by fragglet** [comment]
I'd also be happy with just detecting "Mesa" as the OpenGL vendor, maybe that's an option? Should be sufficient to just print something helpful to stdout.

**Comment by fragglet** [comment]
So as an extra data point: I changed the SDL_CreateRenderer() call in i_video.c to include SDL_RENDERER_SOFTWARE in the flags and suddenly everything is playable again. The takeaway would seem to be that SDL's software renderer/scaling is actually pretty good, better than using Mesa's software scaling.

If we can devise a reliable way to detect when no software rendering is available, we can probably use  that as a fallback. It would be nice to have a config file variable to allow the renderer type to be explicitly specified so that users can force this behavior if necessary without needing to recompile.

**Comment by fragglet** [comment]
The bad news: it seems like the software renderer can't do linear interpolation for scaling, so the screen looks awful :/

**Comment by fragglet** [comment]
@jmtd Thanks for the new option. At least we have something we can point people at as a stopgap.

The only additional thing I'd like to see is something like what was originally discussed - detection of Mesa / software rendering and a message printed to stdout. It will be nice if people can get some hint as to why their game is running so slow.

**Comment by jmtd** [comment]
I had a further look at Mesa detection and I don't think it's possible through SDL2, but if we are happy to use the standard GL headers we can probably get it that way.

One odd thing I noticed: software emulation seems to outperform real HW acceleration for me on my laptop, at least for one timedemo.

**Comment by jmtd** [comment]
I wondered if there were any tweaks we could make to our new pipeline to speed it up further. One thing might be to use HW for the palette conversion. Ryan Coleman shows an approach using shaders here: https://forums.libsdl.org/viewtopic.php?t=8979&sid=f63960cd40b7db23795ab5ab6ca8c6f9

**Comment by jmtd** [comment]
For via VNC, my GL_VENDOR is set to "VMWare, Inc"; seemingly due to use of the [Gallium llvmpipe software rasterizer](http://www.mesa3d.org/llvmpipe.html). So a simple check for "Mesa" isn't good enough. I suspect a check for Mesa and "VMWare" would be too wide (there are probably genuine VMWare HW accelerators, I think they have some pass-through thing for workstation etc.?)

**Comment by jmtd** [comment]
OK the return from SDL_GL_GetProcAddress is null for me on windows, no matter where I put CheckGLVersion, but it fails gracefully so I'll merge as-is, we could return to this in the future if we had performance issues for windows users.
