### ISSUE TITLE
DOOM 2 master levels launcher

### ISSUE THREAD

**Issue by CraftedPixel** [chocolate-doom/chocolate-doom#743]
Is it possible to have a launcher for the doom 2 master levels instead of having to chocolate-doom -file '~/Desktop/games/doomwads/masterlevels/ATTACK.WAD' for every wad.

P.S.
A. . . mistake was made: https://github.com/freedoom/freedoom/issues/258

**Comment by CraftedPixel** [comment]
Do you think you can make a launcher like this?
![iu](https://cloud.githubusercontent.com/assets/15057640/16538425/f00a80fc-3fd8-11e6-9e5f-bec619e4462f.jpeg)
You can name it `chocolate-masterlevels` or something like that.

**Comment by a-detiste** [comment]
https://wiki.debian.org/Games/MasterLevelsForDoomII

**Comment by a-detiste** [comment]
What's this thing ? I'm interrested in screeshots of "PLAY RESULTS" and "OPTIONS" tabs.

**Comment by a-detiste** [comment]
So this is already available for Debian & Debian-derived (Ubuntu-something). There's an unofficial package for OpenSuse somewhere & work in plans for Fedora/RPMFusion

**Comment by jmtd** [comment]
Wow that's part of game-data-packager? My baby has grown a lot since I last worked on her!

It would be quite fun to have a libtextscreen  app to do this

**Comment by jmtd** [comment]
I've never used the original master levels launcher, but I used several similar things from shovel ware CDs in the 90s. If *this* project were to add a launcher, then there's an argument that cloning the master levels launcher makes sense since it has some Id "legitimacy". The other argument would be to design something best of breed that could launch other things than master levels and had any features from other launchers (like the d!zone ones) that master levels lacked.

**Comment by a-detiste** [comment]
I was thinking of making the laucher shipped with game-data-packager also work with Python Urwid library.

**Comment by fragglet** [comment]
Dupe of #434.

**Comment by nicoku007** [comment]
Hi. I recently created a launcher called Choco-Master-Menu, which is available on idgames; among its features, it includes a section for the Master Levels. You can view the launcher in my repository.  https://github.com/nicoku007/Choco-Master-Menu-v1.1
