### ISSUE TITLE
MSVC stuff out of date

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#751]
The msvc folder is out of date again. This is not really news (and on it's own is not really issue-worthy I suppose), but there's a couple of things I propose.

Firstly this could be fixed up for the sdl2-branch so we have a working MSVC project at the beginning of v3. I would suggest we migrate to a VC2015 project, since that's currently freely available for people.

If we add "lib" to the linker path and "include" to the include path (which map to msvc/include and msvc/lib) we can simplify the instructions for the SDL dependencies to "for each SDL2/SDL2_mixer/SDL2_net/SDL2_image zip, extract the lib/x86 files to msvc/lib and the include/ files to msvc/include). Hopefully we can specify these two directories in one place (the "solution"?) and all the projects will inherit them.

We could simplify it even further if we looked at NuGet for fetching the SDL dependencies.

We need to decide whether we are building an x86 target or an amd64 one.

Finally there are a number of SaaS services that could be used for building the msvc project in the cloud, including triggering new builds on each commit. E.g. Visual Studio Team Services https://www.visualstudio.com or possibly https://www.appveyor.com. 

Finally out of scope for this bug (so I will raise this discussion elsewhere I guess) but i think we should promote the MSVC build process to be the "official/blessed" one for Windows. Rationale in brief: the argument against has generally been that it bit-rots quickly, but the same is true for the official instructions -- cross-building from Linux is different enough to doing it natively" via cygwin that those instructions have bit-rotted too. Anecdotally after a few hours the other night I managed to get MSVC working again but I failed to get cygwin set up properly (and I'm a UNIX oriented person!). I'd suggest that cygwin and/or cross-compiling is relatively niche and expert enough that it's a lot to expect of potential windows-based contributors (but experts such as us can put up with the difficulties for convenience of building on our preferred environments if we choose). IF we set up a CI thing as per the last paragraph, we are going to notice/catch the MSVC route bit-rotting much more quickly. Oh and as an aside-inside-an-aside, cygwin-on-windows has mingw-built SDL2 packages available for it, so we don't need to (and probably shouldn't suggest) that folks build SDL from source as a prerequisite for chocolate doom.

**Comment by fragglet** [comment]
> i think we should promote the MSVC build process to be the "official/blessed" one for Windows.

I appreciate the sentiment here; my main problem is that I don't personally have a Windows machine I can use to do this. I usually do the builds for releases so this would leave me unable to do that.

**Comment by jmtd** [comment]
https://github.com/jmtd/chocolate-doom/tree/sdl2-msvc-2015 is a big messy import of the project converted to MS 2015 community edition in need of cleaning up.

> I appreciate the sentiment here; my main problem is that I don't personally have a Windows machine I can use to do this. I usually do the builds for releases so this would leave me unable to do that.

You would still be able to do builds as you do now, even if that method wasn't the one we encouraged others to use (just like the inverse is theoretically true now: windows users can use MSVC to build now, even though the blessed route is cygwin. Except all the instructions are broken :)) -- and if the SaaS/CI stuff works and is any good, you could even do the MSVC builds yourself via a web browser (or simply collect the binaries they spit out)

**Comment by haleyjd** [comment]
I definitely support updating the build tool to 2015, as I intended to eventually provide this myself if nobody else got around to it. However at the same time I was also going to separate out the games into separate solutions, because developing against them with them all in the same solution was very annoying during Choco Strife development and frequently led to us modifying the wrong files due to how the search function works (returns files from all open projects in the solution unless you remember to change the search setting to "Active project only"). I do not know what others' opinions might be on that of course. You could do both, by having a combined .sln that has all 4 projects and a separate .sln with only the common source and each individual game, but that might be viewed as overkill.

**Comment by jmtd** [comment]
> However at the same time I was also going to separate out the games into separate solutions

On a matter like this I would defer to someone who was more likely to use the projects regularly, and so I would go with what you say.

On a related note, adding/editing libs, include paths and lists of files and headers for each game is tedious (e.g. adding i_input.c and h, or removing i_scale). Would a "common" project be possible or would that just lead to more complexity?

**Comment by haleyjd** [comment]
To me that is more complex; settings will have to be kept in sync between builds of both projects.

**Comment by jmtd** [comment]
OK, so leaving out the idea of some kind of common project,

> If we add "lib" to the linker path and "include" to the include path (which map to msvc/include and msvc/lib) we can simplify the instructions for the SDL dependencies to "for each SDL2/SDL2_mixer/SDL2_net/SDL2_image zip, extract the lib/x86 files to msvc/lib and the include/ files to msvc/include). 

What was people's opinions on this? I revoiced it on IRC earlier and some folks seemed happy with the idea.

So I'm proposing I raise a PR which moves the proj files up to current MSVC, and adds a linker path "lib" to each sub-project and include path "include" to each sub-project, so we can then rewrite the MSVC instructions so the users only have to put the includes in one place and the libs in another and won't have to add individual linker or include paths for each sub project (which takes ages!)

Sound OK? This PR would be against master.

**Comment by CapnClever** [comment]
> I'm proposing I raise a PR which moves the proj files up to current MSVC, and adds a linker path "lib" to each sub-project and include path "include" to each sub-project, so we can then rewrite the MSVC instructions so the users only have to put the includes in one place and the libs in another and won't have to add individual linker or include paths for each sub project (which takes ages!)

I second this. As a native Windows user I've been building Chocolate Doom primarily through Visual Studio (managed to get Codeblocks working as well but I'm just more used to VS) and I can say it's a pain having to set up paths on a per-project basis. Newer Visual Studio versions make it a little easier (VS2008 project files have some ridiculous tabbing) but overall it'd be a lot simpler to stash all the necessary files into single locations.

**Comment by haleyjd** [comment]
My other projects are migrating to use of user macros for specifying the include paths and additional library files, so I already have everything necessary to compile and link against SDL2 libraries in my IDE's environment via these. I would suggest that the Chocolate project file follow suit. See Eternity's README.MD file for how it's handled there now.

**Comment by CapnClever** [comment]
> My other projects are migrating to use of user macros for specifying the include paths and additional library files,

I tried these out, they work well. If we're looking into later versions of Visual Studio (user macros require at least VS2012), I'll mess around with additional property sheets to see if I can cut out some project redundancies and make the solution as a whole easier to modify.

**Comment by CapnClever** [comment]
Did some initial work to update the MSVC files more cleanly (what I've been using to develop was hacked together): you can see it at capnclever/chocolate-doom@b4cc2bd. It's by no means complete, especially with the hacking of config.h, but I can use it to build after applying user macros for SDL libraries.

**Comment by jmtd** [comment]
Bumping this, @haleyjd, have you had a chance to look at @CapnClever's branch there? https://github.com/CapnClever/chocolate-doom/commit/b4cc2bd is that something nearly merge-worthy?

**Comment by jmtd** [comment]
...oh I see some comments on the commit itself. Anyway... I just wanted to resurrect the idea of getting the VS files useful again.

**Comment by jmtd** [comment]
Should we target VC (Community) 2017 now?

**Comment by JNechaevsky** [comment]
Alright, I have a good news. I have successfully updated MSVC project to 2017 Community edition, but I'll have to explain everything.

Here's the updated `msvc` folder. To use it, simply remove old `msvc` folder and use this one:
http://jnechaevsky.users.sourceforge.net/files/msvc.zip

**Foreword**

First of all, I must be honest to everyone including myself: after one year of experience, now I'm okay with CodeBlocks and can say/do something about it, but VC is still something definitely new for me, that's why I'm not making any pull request and asking everyone for:

- Double check me.
- Try to compile it. It is great that now it is working for me, but we need it to be working for everyone.
- Explore some ways for optimizing SDL2 libs and headers paths. For some reason, I was not lucky with using one lib/include path for all VC solution, that's why there's a note: _"...for the rest of projects in the solution"._ I know that, for example, it is possible to use exactly one directory for `lib` and one for `include` for every sub-project, but is technically correct?
- Comments, suggestions, corrections are more than welcome. Let's just finish this one year old ticket.

**Why it was not working?**

There was two kind of problems in VC project files: obsolete files from SDL1 version, and missing new files for SDL2. So far, here's all the changes:

libtextscreen: added `txt_conditional.c`
Doom, Heretic, Hexen and Strife: removed `i_scale.c` and added `i_input.c`

That's it. After fixing all of this, everything becomes fine. AFAIR, absolutely same situation was with CodeBlocks project files after switching to SDL2.

## Recommendations for Wiki update

Please use this as draft only. I have covered only the necessary aspects for compiling, but IMO, whole article should be updated properly.

### Step 1: Getting Visual C++
In order to obtain Visual C++ 2017 , go to this link: https://www.visualstudio.com/downloads/

### Step 2: Installing the Development Libraries
Download the VC development libraries for SDL, SDL_mixer and SDL_net. Here are direct links. If they do not work, google for SDL, SDL mixer, SDL net. Make sure you download the 2.x versions!

[SDL2-devel-2.0.5-VC.zip](https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip)
[SDL2_mixer-devel-2.0.1-VC.zip](https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.1-VC.zip)
[SDL2_net-devel-2.0.1-VC.zip](https://www.libsdl.org/projects/SDL_net/release/SDL2_net-devel-2.0.1-VC.zip)

Extract these to a folder inside the top level source code folder called something brilliant like "sdl". These folders contain three key components: .h files for compiling, .lib files for linking, and .dll files for runtime. You must tell Visual Studio where these components are for Chocolate Doom to run.

**.h files**: right click on the **"libopl"** project in Visual Studio and select Properties. Navigate to Configuration Properties -> C/C++ on the left. Click on Additional Include Directories on the right. Add an entry for the include directories for each of the SDL libraries. Assuming you unzipped the libraries into a folder called "sdl" directly under the top level source folder , this would be

- ..\sdl\SDL2-2.0.5\include\
- ..\sdl\SDL2_mixer-2.0.1\include\
- ..\sdl\SDL2_net-2.0.1\include\

**.lib files**: right click on the Chocolate Doom project in Visual Studio and select Properties. Navigate to Configuration Properties -> Linker on the left. Click on Additional Library Directories on the right. Assuming the same directory structure as we had for include files, add the following:

- ..\sdl\SDL2-2.0.5\lib\x86\
- ..\sdl\SDL2_mixer-2.0.1\lib\x86\
- ..\sdl\SDL2_net-2.0.1\lib\x86\

Please also note, you must set these paths for the rest of projects in the solution:

- libpcsound
- libtextscreen
- Setup
- Doom
- Optional: Heretic, Hexen, Strife, Server

**.dll files**: here you have a few options. The simplest one is to just thrown the .dll files into the same directory as the Chocolate Doom executable is being generated. If you are compiling in debug mode this would be `bin\chocolate-*-dbg.exe`, for release it would be `bin\chocolate-*.exe`. Just copy the following files into that directory:

- sdl\SDL2-2.0.5\lib\x86\SDL2.dll
- sdl\SDL2_mixer-2.0.1\lib\x86\SDL2_mixer.dll
- sdl\SDL2_net-2.0.1\lib\x86\SDL2_net.dll

**Comment by JNechaevsky** [comment]
Small but important addition:

1. I have not updated project's version, so it still indicates as 2.3.0. Sorry for my sclerosis.
2. Console output windows is completely optional, it's a MSVC feature. Just need to decide, do we need it or not. See: https://stackoverflow.com/questions/2139637/hide-console-of-windows-application

**Comment by JNechaevsky** [comment]
Colleagues, I have to apologize for "up this thread" behavior, but in terms of Crispy Doom 4.4 I have to do this. (https://github.com/fabiangreffrath/crispy-doom/commit/2917d9aa6affcd6851f6a449b1aae1aea058b6c7#commitcomment-24112089)

Should I do something else with MSVC stuff further?

**Comment by fabiangreffrath** [comment]
Not only in the light of future fork releases, I think that Choco upstream itself would greatly benefit if someone could take care of keeping the MSVC project files up to date (compare the discussion about supported C standards and compilers we had earlier today in https://github.com/chocolate-doom/chocolate-doom/issues/863).

**Comment by fragglet** [comment]
Now fixed, I believe?
