### ISSUE TITLE
Add a means to detect files on case-sensitive file systems

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#809]
As discussed in https://github.com/chocolate-doom/chocolate-doom/pull/807 we should add a function to check for the presence of a given file path using different case variations of its file name.

**Comment by fabiangreffrath** [comment]
I think this will end up as a wrapper around `D_FindWADByName()` which calls this function with different case variations of the file name part of a given path. If it succeeds, it will return the full path with the file name in correct case (as detected by `D_FindWADByName()`) or `NULL` else.

**Comment by fragglet** [comment]
I think if you do it that way then the ordering doesn't make sense. For
example suppose that

DOOMWADPATH=/a/b/c:/d/e/f

Then /a/b/c/DOOM2.WAD (or any other capitalisation) should always take
precedence over /d/e/f/doom2.wad. The ordering in DOOMWADPATH is what
should matter, not capitalisation.

On 17 Nov 2016 7:28 a.m., "Fabian Greffrath" <notifications@github.com>
wrote:

I think this will end up as a wrapper around D_FindWADByName() which calls
this function with different case variations of the file name part of a
given path. If it succeeds, it will return the full path with the file name
in correct case (as detected by D_FindWADByName()) or NULL else.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/chocolate-doom/chocolate-doom/issues/809#issuecomment-261234686>,
or mute the thread

**Comment by fabiangreffrath** [comment]
I see. So, what's probably needed is a wrapper around `M_FileExists()` that's called from within `D_FindWADByName()`.

**Comment by fabiangreffrath** [comment]
How about this?

https://github.com/chocolate-doom/chocolate-doom/compare/master...fabiangreffrath:filecaseexist?expand=1

**Comment by fragglet** [comment]
Now done, I believe?

**Comment by fabiangreffrath** [comment]
Yep, should be all fixed by now.
