### ISSUE TITLE
Setup rebinds duplicate keys

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#81]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/81/) on Sourceforge by [*anonymous](https://sourceforge.net/u/*anonymous/profile/), 2010-08-23 13:35:44:

When configuring the keyboard, the setup application for Chocolate Doom rebinds a previously set command to the default if that key is applied to another command. The setup application by id Software, on the other hand, lets you use keys you already applied over again for other commands.

This is quirk in the original setup application is used sometimes by mouse-using players to bind key_right or key_left and key_strafe to a single key, to create a second key doing the same as another bound to key_straferight or key_strafeleft. This allows the player to effect sr50 movement without having to press a separate strafe key or button.

**Comment by zokum-no** [comment]
Could you make this the default, or at last mention it inside the setup? It took me a while to figure how to do this relatively easy task.

**Comment by fragglet** [comment]
It's already mentioned in the documentation on the wiki, which can be accessed by pressing F1:

https://www.chocolate-doom.org/wiki/index.php/Setup/Keyboard_configuration

**Comment by SpiralBrad** [comment]
Is this 'hold SHIFT to bind multiple keys' thing not working anymore?

From this thread:
> "When you press enter to change a binding, you can now hold down shift to prevent other bindings to the same key from being cleared."

From the wiki page linked:
> "If you want to do this, select the action you want to configure, and hold down the shift key while pressing enter to choose a new key; the other action will not be unbound."

Okay great... so I want to bind 'use' to both 'E' and 'SPACE'.  In the Setup program, I arrow to the key for use (default 'SPACE') and press ENTER, or simply left click it.  I get the 'Press the new key...' dialog.  I press ANY key, _including_ SHIFT, and it instantly rebinds use to that key.  Again, including SHIFT.

There seems to be no way to me to 'hold shift' for multiple keys, because it just rebinds the intended action to shift.

Help?
