### ISSUE TITLE
VGA "porch" border emulation

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#832]
I thought we already had an issue for this, but perhaps the discussion was in another issue, not sure.

Emulate the 8-pixel wide "porch" region of old VGA screen, always filled with current palette colour 0, so defaults to black but flashes when you pick stuff up, etc.

    <directhex> Jon: add support for philips ambilight!

**Comment by fragglet** [comment]
From a brief read it sounds like this isn't really "8 pixels" as such - it depends on your graphics card, monitor and how the monitor is configured (most CRT monitors had controls to adjust the image position and size). But maybe this should just be folded into #793.

A quick thought is that if the real feature request sounds like "bring back the flashes in the black/blank area of the screen". While we don't have CRTs any more, most monitors are widescreen, so we do get that black area still as a border, and it's not currently being used for anything. Maybe we should just tweak the video code to make this show palette color 0 rather than black?

**Comment by jmtd** [comment]
>  While we don't have CRTs any more, most monitors now are widescreen, so we do get that black area still as a border, and it's not currently being used for anything. Maybe we should just tweak the video code to make this show palette color 0 rather than black?

That sounds like a great idea.

**Comment by chungy** [comment]
> While we don't have CRTs any more, most monitors now are widescreen, so we do get that black area still as a border, and it's not currently being used for anything. Maybe we should just tweak the video code to make this show palette color 0 rather than black?

This was the early behavior of Chocolate, but it was fixed to remain black only.

**Comment by AXDOOMER** [comment]
I remember playing in 8 bit mode on my CRT and the screen border did flash when a picked up items. It may  be annoying for some people though.

**Comment by jmtd** [comment]
> This was the early behavior of Chocolate, but it was fixed to remain black only.

Oh yeah: 74c2dc333a383f27ebddf479e3b666a9068d6d36
