### ISSUE TITLE
Scaling seems overly "soft" even at integer scales

### ISSUE THREAD

**Issue by linguica** [chocolate-doom/chocolate-doom#859]
So I tried the new SDL2 beta on my Mac on a 4K display and loaded the game with command line `-width 2560 -height 1920` which is precisely 8x horizontal scaling. This is the result:

![screen shot 2017-02-05 at 11 01 42 am](https://cloud.githubusercontent.com/assets/5770757/22628983/a1438516-eb92-11e6-91e4-70178fb16870.png)

Not only is there obvious resampling on the horizontal axis, it's spread over 2 pixels in between each, uh, texel, for some reason. Even if the rescaler wants to smoothly transition between two texels it should only do so over one pixel, not two. It almost looks like the engine is upscaling to a smaller buffer and then upsampling again.

**Comment by fragglet** [comment]
So the way we do hardware scaling is by (1) doing exact integer scaling into an intermediate texture, then (2) drawing the texture to the screen with nearest scaling. This allows us to do smooth aspect ratio correction while maintaining blockiness. However, we currently impose a limit of 1600x1200 on the size of the intermediate texture:

<https://github.com/chocolate-doom/chocolate-doom/blob/sdl2-branch/src/i_video.c#L590>

The assumption is that beyond 1600x1200 you're using increasing amounts of texture memory for decreasing returns. But yeah, in theory you should only need to see any blurriness in the vertical axis, not the horizontal. Maybe we should bump the limit.

**Comment by fragglet** [comment]
Added a config variable to control the size of the intermediate texture buffer. I've kept 1600x1200 as the default because I still think it's a reasonable default: while in your screenshot the blurriness looks really bad, in reality those digits are less than a centimeter tall and it's basically imperceptible to the naked eye. I tested this out by comparing screenshots of the status bar with and without the blurriness and it's almost impossible to see any difference.

**Comment by fragglet** [comment]
Bumped up to 16M pixels after doing some brief research on modern graphics hardware.

**Comment by fabiangreffrath** [comment]
Does it probably make sense to switch the rendering mode from "linerar" to "nearest" once a certain size for the intermediate texture has exceeded? @JNechaevsky reported a much sharper rendering with this setting here:
https://github.com/JNechaevsky/russian-doom/commit/d3409241dae2c056aeff8d9fe8ff15f94016e102

**Comment by fragglet** [comment]
Well, go back to first principles: suppose you have two pixels (A, B) you want to scale up to 7 pixels. Both A and B get three pixels, and you have one left over as a remainder. Either you (1) make that remainder an average of A and B (what we're doing) or (2) you assign it to A or B. Whether you go with (1) or (2) as a solution has tradeoffs.

In the case of (1) you have something technically "accurate" but with slight blurriness introduced, or in the case of (2) you have no blurriness but pixels get distorted because some are now larger than others. That's exactly what you can see in the screenshots in JNechaevsky/russian-doom@d340924 - it's now less blurry, sure, but if you look closely there's now visible distortion. Check out the top and bottom bars of the "E" on the end of "ЗДОРОВЬЕ" for example - you'll see that the top bar is slightly taller than the bottom bar.

As the screen size increases both of these issues become moot - either the percentage of blurry pixels decreases towards 0 or the amount of distortion decreases towards 0. On balance I'd prefer we retained the current approach - it may be very slightly blurry but at least it's accurate. 

By the way, we only do the whole intermediate texture thing so that we can get this behavior. If you just want to use GL_NEAREST scaling then you can just do that - you don't need an intermediate texture. It's the same as what glboom does, for example.

**Comment by fabiangreffrath** [comment]
Thank you very much for elaborating! Since I start the race with four times the pixels already in Crispy, I sincerely consider to bypass the intermediate texture or at least offer "smoother scaling" merely as an option. Thanks!

**Comment by fabiangreffrath** [comment]
> If you just want to use GL_NEAREST scaling then you can just do that - you don't need an intermediate texture. It's the same as what glboom does, for example.

@fragglet Sorry for asking again, but would you consider adding this as a "hidden" option? the implementation seems pretty straightforward.
