### ISSUE TITLE
Clang compilation produces warnings

### ISSUE THREAD

**Issue by ioan-chera** [chocolate-doom/chocolate-doom#882]
Compiling on macOS, using make, shows the following warnings. Ignore the warnings about libraries.

http://pastebin.com/4ANqMtHW

**Comment by chungy** [comment]
What branch, compiler, and options did you use?

**Comment by ioan-chera** [comment]
master, clang and ./configure CFLAGS=-I/usr/local/include

**Comment by fragglet** [comment]
Changed bug title. It isn't exactly what you reported since there are also the useless "has no symbols" warnings which I don't think we can do much about.

**Comment by turol** [comment]
These are all about useless `abs` function calls. Using it on an unsigned value is no-op. In doom (some of) these appear to have been fixed in c78ca4cf4a5d95b9e0268f43539e61084cdebe9f. They were fixed by explicitly casting to `int`. Doing so might change some behavior, especially the ones in monster logic. The other way to fix these would be to remove the `abs` call since it should have no effect. Which is the correct fix?
