### ISSUE TITLE
Savegame directories for Freedoom

### ISSUE THREAD

**Issue by Catoptromancy** [chocolate-doom/chocolate-doom#896]
~/.local/share/chocolate-doom/savegames/freedoom1.wad/
~/.local/share/chocolate-doom/savegames/freedoom2.wad/

There is a bit of a complication when freedoom uses savegame slots for doom2. Freedoom2 has final doom compatibility so final doom pwads are saved with doom2 savegame slots.

Also Doom2 and Freedoom2 saves are not fully compatible. Flats are random when savegames are loaded with the wrong iwad they were saved with. 
http://www.geocities.ws/catodemos/screenshots/chocosave_doom2.png
http://www.geocities.ws/catodemos/screenshots/chocosave_freedoom2.png

All other iwads have their own savegame directory. Freedoom having its own directories makes sense, and solves some minor issues.

**Comment by fragglet** [comment]
I agree that the Freedoom IWADs should have their own savegame dir.

> Also Doom2 and Freedoom2 saves are not fully compatible. Flats are random when savegames are loaded with the wrong iwad

As an aside: it would be nice if the savegames were compatible; this is an interesting problem, though I'm not sure if it's really solvable. Note that the wall textures are correct; I believe this is because Freedoom has compatibility lists that keep the ordering compatible with the original IWADs (see freedoom/lumps/textures/*/{texture1,texture2,pnames}.txt). In theory we could do the same thing for the flats list too, although it would break with any PWADs that added new flats, so probably it's not worth doing.
