### ISSUE TITLE
Hexen not running

### ISSUE THREAD

**Issue by symbios24** [chocolate-doom/chocolate-doom#911]
Hello, i have a raspberry pi2 with RetroPie v4.2 OS and chocolate doom installed through the extras "https://github.com/zerojay/RetroPie-Extra"

doom/heretic/strife all running except hexen and its expansion once i click to start it returns back to the ports main menu

how can i fix that?

**Comment by jmtd** [comment]
Chocolate Doom as installed via RetroPie-Extra is the "old" version using SDL 1.2.. I'd strongly recommend building sdl2-branch and using that instead.

However your actual problem is likely a missing IWAD. Have you put a copy of hexen.wad somewhere? (probably ~/RetroPie/ports/chocolate-doom)?

If you switch a terminal (outside of emulationstation) and try launching chocolate-hexen, do you get an error message?

**Comment by leilei-** [comment]
If it's not missing you can also try to check the hexen.wad's filename casing

**Comment by jmtd** [comment]
Closing under the assumption that the user did not provide an IWAD. Please feel free to comment further and I'll reopen if it that's not the case.
