### ISSUE TITLE
[suggestion] option to disable automatic scaling of window

### ISSUE THREAD

**Issue by Rahtgaz** [chocolate-doom/chocolate-doom#952]
The current Chocolate behavior of automatically scaling the game window, is a good feature. But it isn't always a friendly feature on Linux systems running tiling window managers, where window cropping can in fact be desirable, or precise dimensioning is required.

I'd like to request an alternative that disables the automatic scaling of the game window. Some implementations ideas:

* a new config option on chocolate-setup screen
* the explicit use of the `-geometry` option on the command line disables automatic scaling. For added benefit, the `-width` and `-height` options could be left alone.
* a new command line option
* the complete removal of this feature

Forgive me if any idea may sound preposterous. The list is just for effect and I don't mean anything by it.

**Comment by fragglet** [comment]
It sounds like this is the same as #331 and the real issue is "Chocolate Doom doesn't work well with tiling window managers". Is that correct? (I'm not sure why that bug was closed)

Rather than adding useless config options I'd rather just fix the problem. Let's make it work properly with tiling window managers so that everyone gets a good experience without having to dig into settings to find out what's wrong.

Before we discuss solutions it would be helpful if you could talk a bit more about what your experience of using Chocolate Doom with a tiling WM is like, what didn't work for you, etc. Why did you find it to be "unfriendly"?

**Comment by fragglet** [comment]
Please read http://xyproblem.info/ - you're proposing a solution, I'd rather understand what the problem is.

Your original comment said this:

> But it isn't always a friendly feature on Linux systems running tiling window managers, where window cropping can in fact be desirable, or precise dimensioning is required.

* In what sense is the current behavior "unfriendly"?
* In what context is window cropping desirable?
* What do you mean by "precise dimensioning" and why do you want it?

Sorry to push back but I want to better understand the full problem here so that we can deliver the best solution.

**Comment by Rahtgaz** [comment]
**What**

Chocolate Doom will scale itself automatically according to the tables in https://www.chocolate-doom.org/wiki/index.php/Screen_resolution, if it needs to shrink or has enough room to grow into the new size.

**In what sense is the current behavior "unfriendly"?**

Under tiling window managers such as i3 or awesome, the large differences between resolutions  (in the tenths and hundreths of pixels on each width and height dimensions) mean that the user control over the layout of his windows becomes too coarse.

For example, playing with a browser window to the left, chocolate on the bottom right and a console on the upper right, means that if I am forced to decide between a 640 width pane or a 512 pane if I am playing with Aspect Ratio on. That's a 128 pixel width difference for my two windows to the right of the browser.

I may choose something in between, but that still forces the scale down and results on a Chocolate pane with a black bar to the right of the game window until I resize it to exactly 512 pixels. This is not behavior users of tiling window managers tend to like.

**In what context is window cropping desirable?**
**What do you mean by "precise dimensioning" and why do you want it?**

With the above in mind, if I can instruct chocolate to not scale the game window automatically, I have a finer control over my window sizes on a tiling WM. Which is the desirable feature, since good control over screen layout is the raison d'être of a tilling window manager. 

For instance, I could be able to crop a few pixels off of Chocolate width or height and still have a perfectly playable window without the game scaling to a much lower window size.

**Comment by fragglet** [comment]
Thanks for the detailed explanation!

> For example, playing with a browser window to the left, chocolate on the bottom right and a console on the upper right, means that if I am forced to decide between a 640 width pane or a 512 pane if I am playing with Aspect Ratio on. That's a 128 pixel width difference for my two windows to the right of the browser.

This is no longer the case with sdl2-branch, since we can now scale to arbitrary resolutions; the tables in the wiki page you've linked to are soon to become obsolete/irrelevant. Can you test chocolate-doom-3.0.0-beta1 and let me know if it works better for you?

**Comment by Rahtgaz** [comment]
I can certainly give it a look after the weekend is over. But being as you describe it, this is certainly not an issue anymore as soon as the sdl2 branch gets its first production release.

For now I'd probably suggest closing this issue since you just answered my main concern.

**Comment by fragglet** [comment]
Great. Please reopen if the new sdl2-branch code doesn't work for you. Thanks for filing this bug.
