### ISSUE TITLE
W_CacheLumpNum: 9260 >= numlumps

### ISSUE THREAD

**Issue by Mastrius0713** [chocolate-doom/chocolate-doom#984]
I did not see this error when searching so I will post it now. when I tried to run multiplayer in either the setup or command line, it gives me a box that says this.
![chocolate doom error](https://user-images.githubusercontent.com/35881000/35477668-f6167dd2-038d-11e8-9aae-fe309e41f65a.JPG)

**Comment by Edward850** [comment]
This has nothing to do with multiplayer. The wad you're trying to load has a fault in it somewhere and is failing to load. Either you haven't designed something to vanilla spec (usually textures being incorrectly defined) or the wad isn't compatible with vanilla/chocolate Doom.

**Comment by fragglet** [comment]
This is likely vanilla behavior and so Chocolate Doom is working as intended; I'm going to optimistically close the bug since I'm fairly certain this is the case.

It's going to be hard to give any advice unless you give details like: (1) what command line you're using to start the game with; (2) what WADs you're trying to load. But a common mistake is using `-file` instead of `-merge` which I believe can cause this error message.
